"""add stage 2 domain models

Revision ID: 0002_domain_models
Revises: 0001_bootstrap
Create Date: 2026-08-04 16:23:14.144153
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_domain_models"
down_revision: str | None = "0001_bootstrap"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "households",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "lifecycle_stage",
            sa.Enum(
                "EARLY_CAREER",
                "FAMILY_FORMATION",
                "PARENTING",
                "MATURE_FAMILY",
                "RETIREMENT_PREPARATION",
                "RETIREMENT_AND_LEGACY",
                name="lifecyclestage",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("region", sa.String(length=120), nullable=False),
        sa.Column("demo_profile", sa.String(length=32), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_households_code"), "households", ["code"], unique=True)
    op.create_index(
        op.f("ix_households_demo_profile"), "households", ["demo_profile"], unique=False
    )
    op.create_index(op.f("ix_households_is_deleted"), "households", ["is_deleted"], unique=False)
    op.create_table(
        "policy_documents",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("issuing_authority", sa.String(length=200), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("source_uri", sa.String(length=500), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_policy_documents_is_deleted"), "policy_documents", ["is_deleted"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("product_type", sa.String(length=80), nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum(
                "R1", "R2", "R3", "R4", "R5", name="productrisklevel", native_enum=False, length=8
            ),
            nullable=False,
        ),
        sa.Column(
            "liquidity_level",
            sa.Enum(
                "IMMEDIATE",
                "WITHIN_7_DAYS",
                "WITHIN_30_DAYS",
                "WITHIN_1_YEAR",
                "ILLIQUID",
                name="liquiditylevel",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("minimum_investment", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("principal_guaranteed", sa.Boolean(), nullable=False),
        sa.Column("guarantee_basis", sa.String(length=300), nullable=True),
        sa.Column("is_simulated", sa.Boolean(), nullable=False),
        sa.Column("terms", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_code"), "products", ["code"], unique=True)
    op.create_index(op.f("ix_products_is_deleted"), "products", ["is_deleted"], unique=False)
    op.create_table(
        "rule_versions",
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("semantic_version", sa.String(length=32), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("rules", sa.JSON(), nullable=False),
        sa.Column("source_summary", sa.String(length=800), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rule_versions_code"), "rule_versions", ["code"], unique=False)
    op.create_index(
        op.f("ix_rule_versions_is_deleted"), "rule_versions", ["is_deleted"], unique=False
    )
    op.create_table(
        "scenario_definitions",
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.String(length=800), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scenario_definitions_code"), "scenario_definitions", ["code"], unique=True
    )
    op.create_index(
        op.f("ix_scenario_definitions_is_deleted"),
        "scenario_definitions",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "account_bucket_plans",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column(
            "bucket",
            sa.Enum(
                "DAILY_LIQUIDITY",
                "RISK_PROTECTION",
                "STABLE_GOALS",
                "LONG_TERM_GROWTH",
                name="accountbucket",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("denominator_name", sa.String(length=80), nullable=False),
        sa.Column("allocated_amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("allocation_ratio", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("constraint_evidence", sa.JSON(), nullable=False),
        sa.Column("rule_version_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rule_version_id"], ["rule_versions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_bucket_plans_household_id"),
        "account_bucket_plans",
        ["household_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_bucket_plans_is_deleted"),
        "account_bucket_plans",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "audit_events",
        sa.Column("household_id", sa.String(length=36), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "CONSENT_GRANTED",
                "CONSENT_WITHDRAWN",
                "DATA_CREATED",
                "DATA_UPDATED",
                "DATA_DELETED",
                "DATA_ACCESSED",
                "CALCULATION_EXECUTED",
                "RECOMMENDATION_GENERATED",
                "REVIEW_RECORDED",
                "CONFIRMATION_RECORDED",
                "MODEL_EXECUTED",
                "RULE_APPLIED",
                name="auditeventtype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(length=80), nullable=False),
        sa.Column("actor_role", sa.String(length=32), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("event_version", sa.Integer(), nullable=False),
        sa.Column("summary", sa.String(length=300), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_household_id"), "audit_events", ["household_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_is_deleted"), "audit_events", ["is_deleted"], unique=False
    )
    op.create_table(
        "behavior_assessments",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("questionnaire_score", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("experiment_score", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column(
            "final_behavior_limit",
            sa.Enum(
                "LOW",
                "MEDIUM_LOW",
                "MEDIUM",
                "MEDIUM_HIGH",
                "HIGH",
                name="risklevel",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("detected_biases", sa.JSON(), nullable=False),
        sa.Column("experiment_answers", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.String(length=800), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_behavior_assessments_household_id"),
        "behavior_assessments",
        ["household_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_behavior_assessments_is_deleted"),
        "behavior_assessments",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "financial_goals",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "goal_type",
            sa.Enum(
                "EMERGENCY_FUND",
                "EDUCATION",
                "HOME",
                "RETIREMENT",
                "MEDICAL",
                "TRAVEL",
                "DEBT_REPAYMENT",
                "FAMILY_SUPPORT",
                "WEALTH_TRANSFER",
                "OTHER",
                name="goaltype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("target_amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column(
            "rigidity",
            sa.Enum(
                "FLEXIBLE", "IMPORTANT", "RIGID", name="goalrigidity", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("can_defer", sa.Boolean(), nullable=False),
        sa.Column("minimum_acceptable_amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("prepared_amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("annual_cost_growth_rate", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_financial_goals_household_id"), "financial_goals", ["household_id"], unique=False
    )
    op.create_index(
        op.f("ix_financial_goals_is_deleted"), "financial_goals", ["is_deleted"], unique=False
    )
    op.create_table(
        "financial_snapshots",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("input_version", sa.String(length=64), nullable=False),
        sa.Column("structured_data", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_financial_snapshots_household_id"),
        "financial_snapshots",
        ["household_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_snapshots_is_deleted"),
        "financial_snapshots",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "household_members",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("relationship", sa.String(length=40), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("occupation", sa.String(length=120), nullable=True),
        sa.Column(
            "employment_stability",
            sa.Enum(
                "LOW", "MEDIUM", "HIGH", name="employmentstability", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("expected_retirement_age", sa.Integer(), nullable=True),
        sa.Column(
            "health_risk_level",
            sa.Enum(
                "LOW",
                "MEDIUM_LOW",
                "MEDIUM",
                "MEDIUM_HIGH",
                "HIGH",
                name="risklevel",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_household_members_household_id"),
        "household_members",
        ["household_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_household_members_is_deleted"), "household_members", ["is_deleted"], unique=False
    )
    op.create_table(
        "model_runs",
        sa.Column("household_id", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=120), nullable=False),
        sa.Column("task", sa.String(length=120), nullable=False),
        sa.Column("prompt_hash", sa.String(length=128), nullable=False),
        sa.Column("redacted_input", sa.JSON(), nullable=False),
        sa.Column("structured_output", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("degraded", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_runs_household_id"), "model_runs", ["household_id"], unique=False
    )
    op.create_index(op.f("ix_model_runs_is_deleted"), "model_runs", ["is_deleted"], unique=False)
    op.create_table(
        "plan_reports",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("report_version", sa.String(length=64), nullable=False),
        sa.Column("chapter_count", sa.Integer(), nullable=False),
        sa.Column("structured_report", sa.JSON(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consistency_status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("chapter_count = 8", name="ck_plan_reports_chapter_count_eight"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_plan_reports_household_id"), "plan_reports", ["household_id"], unique=False
    )
    op.create_index(
        op.f("ix_plan_reports_is_deleted"), "plan_reports", ["is_deleted"], unique=False
    )
    op.create_table(
        "portfolio_plans",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("plan_name", sa.String(length=120), nullable=False),
        sa.Column("candidate_type", sa.String(length=32), nullable=False),
        sa.Column("denominator_name", sa.String(length=80), nullable=False),
        sa.Column("allocations", sa.JSON(), nullable=False),
        sa.Column("suitability_evidence", sa.JSON(), nullable=False),
        sa.Column("optimizer_version", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portfolio_plans_household_id"), "portfolio_plans", ["household_id"], unique=False
    )
    op.create_index(
        op.f("ix_portfolio_plans_is_deleted"), "portfolio_plans", ["is_deleted"], unique=False
    )
    op.create_table(
        "recommendations",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("recommendation_type", sa.String(length=80), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING_REVIEW",
                "APPROVED",
                "REJECTED",
                "CUSTOMER_CONFIRMED",
                "EXECUTED",
                "EXPIRED",
                name="recommendationstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.Column("structured_advice", sa.JSON(), nullable=False),
        sa.Column("suitability_evidence", sa.JSON(), nullable=False),
        sa.Column("rule_version_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rule_version_id"], ["rule_versions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendations_household_id"), "recommendations", ["household_id"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_is_deleted"), "recommendations", ["is_deleted"], unique=False
    )
    op.create_table(
        "risk_assessments",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("capacity_score", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("willingness_score", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("knowledge_score", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("behavior_score", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column(
            "final_risk_limit",
            sa.Enum(
                "LOW",
                "MEDIUM_LOW",
                "MEDIUM",
                "MEDIUM_HIGH",
                "HIGH",
                name="risklevel",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("explanation", sa.String(length=800), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_risk_assessments_household_id"), "risk_assessments", ["household_id"], unique=False
    )
    op.create_index(
        op.f("ix_risk_assessments_is_deleted"), "risk_assessments", ["is_deleted"], unique=False
    )
    op.create_table(
        "action_items",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("recommendation_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("owner_role", sa.String(length=32), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recommendation_id"], ["recommendations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_action_items_household_id"), "action_items", ["household_id"], unique=False
    )
    op.create_index(
        op.f("ix_action_items_is_deleted"), "action_items", ["is_deleted"], unique=False
    )
    op.create_table(
        "advisor_reviews",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=True),
        sa.Column("advisor_id", sa.String(length=80), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("comments", sa.String(length=1000), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["report_id"], ["plan_reports.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_advisor_reviews_household_id"), "advisor_reviews", ["household_id"], unique=False
    )
    op.create_index(
        op.f("ix_advisor_reviews_is_deleted"), "advisor_reviews", ["is_deleted"], unique=False
    )
    op.create_table(
        "assets",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("owner_member_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "CASH",
                "DEMAND_DEPOSIT",
                "MONEY_MARKET",
                "TIME_DEPOSIT",
                "BANK_WEALTH_MANAGEMENT",
                "BOND",
                "BOND_FUND",
                "PUBLIC_FUND",
                "EQUITY_FUND",
                "STOCK",
                "PENSION_ACCOUNT",
                "INSURANCE_CASH_VALUE",
                "TRUST",
                "PRIMARY_RESIDENCE",
                "INVESTMENT_PROPERTY",
                "VEHICLE",
                "OTHER",
                name="assetcategory",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("subcategory", sa.String(length=80), nullable=True),
        sa.Column("acquisition_cost", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("market_value", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("liquidity_days", sa.Integer(), nullable=False),
        sa.Column(
            "liquidity_level",
            sa.Enum(
                "IMMEDIATE",
                "WITHIN_7_DAYS",
                "WITHIN_30_DAYS",
                "WITHIN_1_YEAR",
                "ILLIQUID",
                name="liquiditylevel",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "risk_level",
            sa.Enum(
                "LOW",
                "MEDIUM_LOW",
                "MEDIUM",
                "MEDIUM_HIGH",
                "HIGH",
                name="risklevel",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("purpose", sa.String(length=160), nullable=False),
        sa.Column("pledged", sa.Boolean(), nullable=False),
        sa.Column("ownership", sa.String(length=80), nullable=False),
        sa.Column(
            "property_use",
            sa.Enum(
                "NOT_PROPERTY",
                "PRIMARY_RESIDENCE",
                "INVESTMENT_PROPERTY",
                name="propertyuse",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_member_id"], ["household_members.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assets_household_id"), "assets", ["household_id"], unique=False)
    op.create_index(op.f("ix_assets_is_deleted"), "assets", ["is_deleted"], unique=False)
    op.create_table(
        "consent_records",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("member_id", sa.String(length=36), nullable=True),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("purpose", sa.String(length=300), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consent_version", sa.String(length=32), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["member_id"], ["household_members.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consent_records_household_id"), "consent_records", ["household_id"], unique=False
    )
    op.create_index(
        op.f("ix_consent_records_is_deleted"), "consent_records", ["is_deleted"], unique=False
    )
    op.create_table(
        "customer_confirmations",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=True),
        sa.Column("member_id", sa.String(length=36), nullable=True),
        sa.Column("confirmation_type", sa.String(length=64), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmation_version", sa.String(length=64), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["member_id"], ["household_members.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["report_id"], ["plan_reports.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_confirmations_household_id"),
        "customer_confirmations",
        ["household_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_confirmations_is_deleted"),
        "customer_confirmations",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "expense_items",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("member_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum(
                "MONTHLY",
                "QUARTERLY",
                "ANNUAL",
                "ONE_TIME",
                "IRREGULAR",
                name="cashflowfrequency",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "necessity",
            sa.Enum("ESSENTIAL", "FLEXIBLE", name="expensenecessity", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("compressible_ratio", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("seasonality", sa.JSON(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "BASIC_LIVING",
                "DISCRETIONARY",
                "PARENT_SUPPORT",
                "CHILD_EDUCATION",
                "MEDICAL",
                "INSURANCE_PREMIUM",
                "DEBT_SERVICE",
                "TAX",
                "OTHER",
                name="expensecategory",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["member_id"], ["household_members.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expense_items_household_id"), "expense_items", ["household_id"], unique=False
    )
    op.create_index(
        op.f("ix_expense_items_is_deleted"), "expense_items", ["is_deleted"], unique=False
    )
    op.create_table(
        "financial_metrics",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("metric_code", sa.String(length=80), nullable=False),
        sa.Column("value", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("numerator", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("denominator", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("formula_version", sa.String(length=64), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["financial_snapshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_financial_metrics_household_id"),
        "financial_metrics",
        ["household_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_metrics_is_deleted"), "financial_metrics", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_financial_metrics_snapshot_id"), "financial_metrics", ["snapshot_id"], unique=False
    )
    op.create_table(
        "income_sources",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("member_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum(
                "MONTHLY",
                "QUARTERLY",
                "ANNUAL",
                "ONE_TIME",
                "IRREGULAR",
                name="cashflowfrequency",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("stability", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("volatility", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("interruption_probability", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("cycle_correlation", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("source_concentration", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("is_sustainable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["member_id"], ["household_members.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_income_sources_household_id"), "income_sources", ["household_id"], unique=False
    )
    op.create_index(
        op.f("ix_income_sources_is_deleted"), "income_sources", ["is_deleted"], unique=False
    )
    op.create_table(
        "insurance_policies",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("insured_member_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "policy_type",
            sa.Enum(
                "TERM_LIFE",
                "WHOLE_LIFE",
                "MEDICAL",
                "CRITICAL_ILLNESS",
                "ACCIDENT",
                "ANNUITY",
                "PROPERTY",
                "OTHER",
                name="insurancetype",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("coverage_amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("annual_premium", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("deductible", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("waiting_period_days", sa.Integer(), nullable=False),
        sa.Column("guaranteed_benefit", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("non_guaranteed_benefit", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("cash_value", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["insured_member_id"], ["household_members.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_insurance_policies_household_id"),
        "insurance_policies",
        ["household_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_insurance_policies_is_deleted"), "insurance_policies", ["is_deleted"], unique=False
    )
    op.create_table(
        "simulation_runs",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("scenario_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=True),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("engine_version", sa.String(length=64), nullable=False),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("outputs", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scenario_id"], ["scenario_definitions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["financial_snapshots.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_simulation_runs_household_id"), "simulation_runs", ["household_id"], unique=False
    )
    op.create_index(
        op.f("ix_simulation_runs_is_deleted"), "simulation_runs", ["is_deleted"], unique=False
    )
    op.create_table(
        "social_security_accounts",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("member_id", sa.String(length=36), nullable=False),
        sa.Column("account_type", sa.String(length=64), nullable=False),
        sa.Column("balance", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column(
            "annual_personal_contribution", sa.Numeric(precision=20, scale=2), nullable=False
        ),
        sa.Column(
            "annual_employer_contribution", sa.Numeric(precision=20, scale=2), nullable=False
        ),
        sa.Column("benefit_region", sa.String(length=120), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["member_id"], ["household_members.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_social_security_accounts_household_id"),
        "social_security_accounts",
        ["household_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_social_security_accounts_is_deleted"),
        "social_security_accounts",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "liabilities",
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("borrower_member_id", sa.String(length=36), nullable=True),
        sa.Column("linked_asset_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "MORTGAGE",
                "AUTO_LOAN",
                "CONSUMER_LOAN",
                "CREDIT_CARD_UNPAID",
                "BANK_LOAN",
                "NON_BANK_LOAN",
                "OTHER",
                name="liabilitycategory",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("outstanding_balance", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("annual_interest_rate", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("monthly_payment", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("maturity_date", sa.Date(), nullable=True),
        sa.Column(
            "rate_type",
            sa.Enum("FIXED", "FLOATING", name="ratetype", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("prepayment_cost", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("is_high_interest", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("is_user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["borrower_member_id"], ["household_members.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["linked_asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_liabilities_household_id"), "liabilities", ["household_id"], unique=False
    )
    op.create_index(op.f("ix_liabilities_is_deleted"), "liabilities", ["is_deleted"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_liabilities_is_deleted"), table_name="liabilities")
    op.drop_index(op.f("ix_liabilities_household_id"), table_name="liabilities")
    op.drop_table("liabilities")
    op.drop_index(
        op.f("ix_social_security_accounts_is_deleted"), table_name="social_security_accounts"
    )
    op.drop_index(
        op.f("ix_social_security_accounts_household_id"), table_name="social_security_accounts"
    )
    op.drop_table("social_security_accounts")
    op.drop_index(op.f("ix_simulation_runs_is_deleted"), table_name="simulation_runs")
    op.drop_index(op.f("ix_simulation_runs_household_id"), table_name="simulation_runs")
    op.drop_table("simulation_runs")
    op.drop_index(op.f("ix_insurance_policies_is_deleted"), table_name="insurance_policies")
    op.drop_index(op.f("ix_insurance_policies_household_id"), table_name="insurance_policies")
    op.drop_table("insurance_policies")
    op.drop_index(op.f("ix_income_sources_is_deleted"), table_name="income_sources")
    op.drop_index(op.f("ix_income_sources_household_id"), table_name="income_sources")
    op.drop_table("income_sources")
    op.drop_index(op.f("ix_financial_metrics_snapshot_id"), table_name="financial_metrics")
    op.drop_index(op.f("ix_financial_metrics_is_deleted"), table_name="financial_metrics")
    op.drop_index(op.f("ix_financial_metrics_household_id"), table_name="financial_metrics")
    op.drop_table("financial_metrics")
    op.drop_index(op.f("ix_expense_items_is_deleted"), table_name="expense_items")
    op.drop_index(op.f("ix_expense_items_household_id"), table_name="expense_items")
    op.drop_table("expense_items")
    op.drop_index(op.f("ix_customer_confirmations_is_deleted"), table_name="customer_confirmations")
    op.drop_index(
        op.f("ix_customer_confirmations_household_id"), table_name="customer_confirmations"
    )
    op.drop_table("customer_confirmations")
    op.drop_index(op.f("ix_consent_records_is_deleted"), table_name="consent_records")
    op.drop_index(op.f("ix_consent_records_household_id"), table_name="consent_records")
    op.drop_table("consent_records")
    op.drop_index(op.f("ix_assets_is_deleted"), table_name="assets")
    op.drop_index(op.f("ix_assets_household_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_advisor_reviews_is_deleted"), table_name="advisor_reviews")
    op.drop_index(op.f("ix_advisor_reviews_household_id"), table_name="advisor_reviews")
    op.drop_table("advisor_reviews")
    op.drop_index(op.f("ix_action_items_is_deleted"), table_name="action_items")
    op.drop_index(op.f("ix_action_items_household_id"), table_name="action_items")
    op.drop_table("action_items")
    op.drop_index(op.f("ix_risk_assessments_is_deleted"), table_name="risk_assessments")
    op.drop_index(op.f("ix_risk_assessments_household_id"), table_name="risk_assessments")
    op.drop_table("risk_assessments")
    op.drop_index(op.f("ix_recommendations_is_deleted"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_household_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_portfolio_plans_is_deleted"), table_name="portfolio_plans")
    op.drop_index(op.f("ix_portfolio_plans_household_id"), table_name="portfolio_plans")
    op.drop_table("portfolio_plans")
    op.drop_index(op.f("ix_plan_reports_is_deleted"), table_name="plan_reports")
    op.drop_index(op.f("ix_plan_reports_household_id"), table_name="plan_reports")
    op.drop_table("plan_reports")
    op.drop_index(op.f("ix_model_runs_is_deleted"), table_name="model_runs")
    op.drop_index(op.f("ix_model_runs_household_id"), table_name="model_runs")
    op.drop_table("model_runs")
    op.drop_index(op.f("ix_household_members_is_deleted"), table_name="household_members")
    op.drop_index(op.f("ix_household_members_household_id"), table_name="household_members")
    op.drop_table("household_members")
    op.drop_index(op.f("ix_financial_snapshots_is_deleted"), table_name="financial_snapshots")
    op.drop_index(op.f("ix_financial_snapshots_household_id"), table_name="financial_snapshots")
    op.drop_table("financial_snapshots")
    op.drop_index(op.f("ix_financial_goals_is_deleted"), table_name="financial_goals")
    op.drop_index(op.f("ix_financial_goals_household_id"), table_name="financial_goals")
    op.drop_table("financial_goals")
    op.drop_index(op.f("ix_behavior_assessments_is_deleted"), table_name="behavior_assessments")
    op.drop_index(op.f("ix_behavior_assessments_household_id"), table_name="behavior_assessments")
    op.drop_table("behavior_assessments")
    op.drop_index(op.f("ix_audit_events_is_deleted"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_household_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_account_bucket_plans_is_deleted"), table_name="account_bucket_plans")
    op.drop_index(op.f("ix_account_bucket_plans_household_id"), table_name="account_bucket_plans")
    op.drop_table("account_bucket_plans")
    op.drop_index(op.f("ix_scenario_definitions_is_deleted"), table_name="scenario_definitions")
    op.drop_index(op.f("ix_scenario_definitions_code"), table_name="scenario_definitions")
    op.drop_table("scenario_definitions")
    op.drop_index(op.f("ix_rule_versions_is_deleted"), table_name="rule_versions")
    op.drop_index(op.f("ix_rule_versions_code"), table_name="rule_versions")
    op.drop_table("rule_versions")
    op.drop_index(op.f("ix_products_is_deleted"), table_name="products")
    op.drop_index(op.f("ix_products_code"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_policy_documents_is_deleted"), table_name="policy_documents")
    op.drop_table("policy_documents")
    op.drop_index(op.f("ix_households_is_deleted"), table_name="households")
    op.drop_index(op.f("ix_households_demo_profile"), table_name="households")
    op.drop_index(op.f("ix_households_code"), table_name="households")
    op.drop_table("households")
    # ### end Alembic commands ###
