import type {
  BehaviorABFramework,
  BehaviorCatalog,
  BehaviorOverview,
  BehaviorProfile,
  BehaviorSession,
} from "../api/behavior";

export const behaviorCatalogFixture: BehaviorCatalog = {
  rule_version: "1.0.0",
  formula_version: "behavior-scoring-1.0.0",
  experiment_version: "behavior-experiments-1.0.0",
  ab_framework_version: "behavior-ab-1.0.0",
  source_type: "internal_demo",
  source_summary: "测试夹具中的内部演示行为规则；不是监管统一评级标准。",
  questionnaire_dimensions: ([
    ["risk_willingness", "风险意愿"],
    ["loss_tolerance_claim", "自述损失承受"],
    ["investment_experience", "投资经验"],
    ["knowledge", "金融知识"],
    ["trading_frequency", "交易克制度"],
    ["attention", "注意力稳定"],
    ["goal_discipline", "目标纪律"],
  ] as const).map(([code, name]) => ({
    code: code as keyof import("../api/behavior").BehaviorQuestionnaire,
    name: name ?? code,
    prompt: `${name}测试问题`,
    low_label: "低",
    high_label: "高",
    weight: code === "risk_willingness" || code === "loss_tolerance_claim" ? "0.200000" : code === "investment_experience" || code === "knowledge" ? "0.150000" : code === "trading_frequency" ? "0.100000" : code === "attention" ? "0.080000" : "0.120000",
  })),
  experiments: [
    ["market_up_20", "上涨 20% 后", [["keep_plan", "保持计划"], ["chase_add", "立即大幅加仓"]]],
    ["market_down_10", "下跌 10% 后", [["hold_plan", "保持计划"], ["sell_all", "立即全部卖出"]]],
    ["market_down_30", "下跌 30% 后", [["hold_plan", "保持计划"], ["sell_all", "立即全部卖出"]]],
    ["hot_product_choice", "热门高收益叙事", [["choose_suitable", "选择适配方案"], ["chase_hot", "因热度立即买入"]]],
    ["winner_loser_disposal", "盈利与亏损资产处置", [["rebalance_by_target", "按目标再平衡"], ["hold_until_entry", "等回买入价"]]],
    ["consume_or_goal", "立即消费与未来目标", [["goal_first", "优先目标"], ["split_by_rule", "按规则分配"]]],
  ].map(([code, name, options]) => ({
    code: code as string,
    name: name as string,
    scenario: `${name as string}的测试情景。`,
    options: (options as string[][]).map(([optionCode, label]) => ({ code: optionCode ?? "", label: label ?? "" })),
  })),
  bias_definitions: [
    "loss_aversion", "overconfidence", "herding", "recency_bias", "disposition_effect", "anchoring", "familiarity_bias", "mental_accounting", "present_bias", "performance_chasing", "frequent_trading_tendency",
  ].map((code) => ({ code, name: code, description: `${code} 说明` })),
  intervention_definitions: Array.from({ length: 12 }, (_, index) => ({
    code: `intervention_${index}`,
    name: `干预 ${index + 1}`,
    trigger_biases: ["loss_aversion"],
    scenario_code: "test",
    action_instruction: "按目标复核。",
  })),
  ab_variants: [
    { code: "ordinary_prompt", name: "普通提示", description: "统一提示" },
    { code: "personalized_prompt", name: "个性化提示", description: "偏差与目标提示" },
    { code: "twin_loss_simulation", name: "数字孪生损失模拟", description: "金额化损失" },
    { code: "cooling_goal_reminder", name: "冷静期／目标提醒", description: "冷静与目标" },
  ],
  required_experiment_count: 6,
  behavior_boundary: "问卷与实验只用于审慎下调；最终风险上限不得高于客观承担能力。",
};

const biasNames: Record<string, string> = {
  loss_aversion: "损失厌恶",
  overconfidence: "过度自信",
  herding: "从众",
  recency_bias: "近期偏差",
  disposition_effect: "处置效应",
  anchoring: "锚定",
  familiarity_bias: "熟悉性偏差",
  mental_accounting: "心理账户",
  present_bias: "现时偏好",
  performance_chasing: "追涨杀跌",
  frequent_trading_tendency: "频繁交易倾向",
};

const biasScores: Record<string, string> = {
  loss_aversion: "1.000000",
  overconfidence: "0.600000",
  herding: "1.000000",
  recency_bias: "0.900000",
  disposition_effect: "0.050000",
  anchoring: "0.050000",
  familiarity_bias: "0.550000",
  mental_accounting: "0.300000",
  present_bias: "0.450000",
  performance_chasing: "1.000000",
  frequent_trading_tendency: "0.500000",
};

export const behaviorProfileFixture: BehaviorProfile = {
  meta: {
    household_id: "household-b",
    household_code: "DEMO_B",
    household_name: "B 家庭（测试夹具）",
    analysis_date: "2026-08-04",
    data_as_of: "2026-08-04",
    source: "synthetic_behavior_input",
    source_type: "synthetic_or_authorized_test_data",
    rule_version: "1.0.0",
    formula_version: "behavior-scoring-1.0.0",
    experiment_version: "behavior-experiments-1.0.0",
    input_version: "behavior-fixture-input-version",
    calculation_source: "deterministic_behavior_engine",
  },
  dual_profile: {
    objective_capacity_score: "0.580000",
    objective_capacity_limit: "medium",
    questionnaire_score: "0.632000",
    questionnaire_claim_limit: "medium_high",
    experiment_score: "0.503333",
    experiment_limit: "low",
    behavioral_limit_before_capacity: "low",
    effective_risk_limit: "low",
    risk_downshifted: true,
    conflict_detected: true,
    conflict_codes: ["claimed_30_percent_but_sold_at_10_percent", "buy_after_rise_sell_after_fall"],
    explanation: "问卷与真实选择存在冲突，最终取客观能力、问卷和实验的审慎最低值；行为结果不能提高客观能力。",
    capacity_source_record_id: "risk-fixture-record",
  },
  biases: Object.keys(biasNames).map((code) => {
    const score = biasScores[code] ?? "0.000000";
    const numeric = Number(score);
    return {
      code,
      name: biasNames[code] ?? code,
      description: `${biasNames[code] ?? code}的测试解释。`,
      score,
      severity: numeric > 0.59 ? "high" as const : numeric > 0.29 ? "watch" as const : "low" as const,
      evidence: [{ source: `experiment.${code}`, source_label: "行为实验", observation: `${biasNames[code] ?? code}选择证据。`, contribution: score }],
      explanation: "该分数只用于干预与审慎下调。",
    };
  }),
  interventions: [
    {
      intervention_id: null,
      code: "cooling_period",
      name: "24／48 小时冷静期",
      status: "active",
      trigger_biases: ["performance_chasing", "herding", "recency_bias"],
      scenario_code: "impulse_trade",
      linked_goal_id: "goal-education",
      linked_goal_name: "子女高等教育",
      personalized_message: "B 家庭出现追涨杀跌与从众证据；计划外交易先暂停 48 小时。",
      action_instruction: "结束后复核目标、适当性和金额化损失，不自动执行交易。",
      cooling_period_hours: 48,
      starts_at: null,
      eligible_at: null,
      completed_at: null,
      dismissed_at: null,
      assigned_variant: "ordinary_prompt",
      audit_note: "预览；完成实验后才写入可审计干预记录。",
    },
    {
      intervention_id: null,
      code: "counterfactual_rehearsal",
      name: "反事实与下跌前预演",
      status: "active",
      trigger_biases: ["loss_aversion", "performance_chasing"],
      scenario_code: "loss_rehearsal",
      linked_goal_id: "goal-education",
      linked_goal_name: "子女高等教育",
      personalized_message: "根据损失厌恶与追涨杀跌证据，先预演下跌情景。",
      action_instruction: "关键金额读取确定性数字孪生，不由语言模型心算。",
      cooling_period_hours: null,
      starts_at: null,
      eligible_at: null,
      completed_at: null,
      dismissed_at: null,
      assigned_variant: "ordinary_prompt",
      audit_note: "预览；完成实验后才写入可审计干预记录。",
    },
  ],
  responses: behaviorCatalogFixture.experiments.map((experiment, index) => ({
    response_id: `response-${index}`,
    experiment_code: experiment.code,
    choice_code: experiment.options[1]?.code ?? experiment.options[0]?.code ?? "choice",
    choice_label: experiment.options[1]?.label ?? experiment.options[0]?.label ?? "选择",
    response_time_ms: 1800 + index * 300,
    modification_count: index % 2,
    consistency_score: "0.700000",
    answered_at: "2026-08-04T08:00:00Z",
    evidence: "测试选择证据。",
  })),
  assigned_variant: "ordinary_prompt",
  assigned_variant_name: "普通提示",
  average_response_time_ms: 2833,
  total_modification_count: 6,
  overall_consistency_score: "0.716667",
  limitations: ["行为评分不是监管评级。", "干预不保证收益或避免损失。"],
};

export const behaviorOverviewFixture: BehaviorOverview = {
  household_id: "household-b",
  information_status: "sufficient",
  information_message: "已获得完整问卷与六项实验。",
  profile: behaviorProfileFixture,
  latest_session: null,
  can_start_experiment: true,
  authorization_basis: "synthetic_data",
  limitations: ["仅处理合成或授权测试数据。"],
};

export function behaviorSessionFixture(answeredCount = 0, profile: BehaviorProfile | null = null): BehaviorSession {
  const answered = behaviorProfileFixture.responses.slice(0, answeredCount);
  return {
    session_id: "behavior-session-fixture",
    household_id: "household-b",
    status: profile ? "completed" : "active",
    information_status: profile ? "sufficient" : "collecting",
    answered_count: answeredCount,
    required_count: 6,
    remaining_experiment_codes: behaviorCatalogFixture.experiments.slice(answeredCount).map((item) => item.code),
    assigned_variant: "personalized_prompt",
    assigned_variant_name: "个性化提示",
    experiment_key: "behavior_nudge_main",
    questionnaire_score: "0.632000",
    questionnaire_claim_limit: "medium_high",
    objective_capacity_limit: "medium",
    effective_risk_limit: profile ? "low" : null,
    started_at: "2026-08-04T08:00:00Z",
    completed_at: profile ? "2026-08-04T08:05:00Z" : null,
    exited_at: null,
    responses: answered,
    profile,
  };
}

export const behaviorABFixture: BehaviorABFramework = {
  framework_version: "behavior-ab-1.0.0",
  experiment_key: "behavior_nudge_main",
  eligible_data_policy: "仅统计合成或明确授权测试会话",
  variants: behaviorCatalogFixture.ab_variants,
  metrics: behaviorCatalogFixture.ab_variants.map((item, index) => ({
    variant_code: item.code,
    variant_name: item.name,
    assigned_count: index === 0 ? 3 : 0,
    completed_count: index === 0 ? 2 : 0,
    exited_count: index === 0 ? 1 : 0,
    completion_rate: index === 0 ? "0.666667" : null,
    average_response_time_ms: index === 0 ? 2833 : null,
    risk_downshift_count: index === 0 ? 2 : 0,
    intervention_completed_count: 0,
  })),
  metric_definitions: { completion_rate: "完成会话数 ÷ 分配会话数" },
  privacy_note: "指标不代表投资收益或干预因果效果。",
};
