import type { CFSSolutionResponse } from "../api/cfs";

export const cfsFixture = {
  meta: {
    household_id: "household-b",
    analysis_date: "2026-08-10",
    data_as_of: "2026-08-10",
    source_snapshot_id: "snapshot-cfs-b",
    rule_version: "1.0.0",
    formula_version: "cfs-orchestration-v1",
    calculation_source: "deterministic_tools",
    idempotent_replay: false,
  },
  solution: {
    id: "solution-b",
    household_id: "household-b",
    source_snapshot_id: "snapshot-cfs-b",
    solution_version: 1,
    status: "needs_review",
    summary: {
      headline: "先还债，当前不新增投资",
      no_action_required: true,
      boundary: "CFS 先确定目的、金额、风险预算、工具与专业路由；产品本体只在通过映射闸门后，以独立候选层承接。",
    },
    decision_hash: "cfs-decision-hash-0123456789",
    risk_budget_version: "cfs-orchestration-v1:0123456789ab",
  },
  components: [
    {
      id: "component-debt",
      solution_id: "solution-b",
      wealth_need_id: "need-debt",
      component_type: "debt",
      priority: 1,
      target_amount: "1208000.00",
      minimum_amount: "8000.00",
      time_horizon: "immediate",
      recommended_action: "优先偿还高息债务，再评估长期配置。",
      product_mapping_allowed: false,
      professional_review_required: false,
      required_specialist: null,
      status: "recommended",
      rationale: "需求优先级 #1；存在待处理的高息债务。",
      evidence: { deterministic_tool: "liability_calendar" },
      currency: "CNY",
    },
    {
      id: "component-protection",
      solution_id: "solution-b",
      wealth_need_id: "need-protection",
      component_type: "protection",
      priority: 2,
      target_amount: "1080000.00",
      minimum_amount: "1080000.00",
      time_horizon: "ongoing",
      recommended_action: "先核对保障缺口与可持续保费。",
      product_mapping_allowed: false,
      professional_review_required: true,
      required_specialist: "insurance_specialist",
      status: "professional_review_required",
      rationale: "保障缺口需要由专业人员核对。",
      evidence: { deterministic_tool: "protection_planner" },
      currency: "CNY",
    },
    {
      id: "component-no-action",
      solution_id: "solution-b",
      wealth_need_id: "need-growth",
      component_type: "no_action",
      priority: 6,
      target_amount: "2490000.00",
      minimum_amount: "0.00",
      time_horizon: "long_term",
      recommended_action: "当前不新增投资，先完成前置责任并等待风险预算重新开放。",
      product_mapping_allowed: false,
      professional_review_required: false,
      required_specialist: null,
      status: "no_action_required",
      rationale: "先实际偿还高息债务，再开放长期配置。",
      evidence: { deterministic_tool: "no_action" },
      currency: "CNY",
    },
  ],
  risk_budget: {
    factors: [
      { code: "capacity", label: "风险承担能力", level: "medium", amount: "0.00", ratio: "0.000000", explanation: "由收入、资产负债和责任期限决定。" },
      { code: "willingness", label: "风险承担意愿", level: "medium_high", amount: "0.00", ratio: "0.000000", explanation: "使用有效风险评估。" },
      { code: "behavior", label: "行为承受上限", level: "medium", amount: "0.00", ratio: "0.000000", explanation: "真实行为边界限制过高意愿。" },
      { code: "existing_economic_exposure", label: "现有经济权益暴露", level: null, amount: "560000.00", ratio: "0.082450", explanation: "同时纳入证券与家企暴露。" },
      { code: "liquidity", label: "流动性安全垫", level: null, amount: "205800.00", ratio: "1.000000", explanation: "显示日常周转与应急缺口。" },
      { code: "liability_rigidity", label: "刚性责任", level: null, amount: "1208000.00", ratio: "0.177857", explanation: "刚性责任缺口会收紧风险预算。" },
      { code: "time_horizon", label: "最短责任期限", level: null, amount: "30.00", ratio: "0.027397", explanation: "最近一笔责任约束可承受风险。" },
    ],
    capacity: "medium",
    willingness: "medium_high",
    behavior: "medium",
    household_economic_risk_capacity: "low",
    existing_economic_exposure: "560000.00",
    economic_exposure_ratio: "0.082450",
    liquidity_reserve_required: "205800.00",
    liquidity_gap: "205800.00",
    rigid_liability_target: "1208000.00",
    rigid_liability_gap: "1208000.00",
    shortest_time_horizon_days: 30,
    risk_ceiling_ratio: "0.200000",
    risk_ceiling_amount: "1358400.00",
    remaining_risk_capacity: "0.00",
    additional_risk_allowed: false,
    decision: "repair_first",
    constraints: ["先实际偿还高息债务，再开放长期配置。"],
    input_hash: "risk-budget-input-hash",
    version: "cfs-orchestration-v1:0123456789ab",
    explanation: "Risk Budget 表示 household economic risk capacity，不是单一 R1-R5 标签。",
  },
  orchestration: [
    { component_id: "component-debt", purpose: "debt", allowed_risk: "low", deterministic_tool: "liability_calendar", status: "ready", output_summary: "优先偿还高息债务。" },
    { component_id: "component-protection", purpose: "protection", allowed_risk: "low", deterministic_tool: "protection_planner", status: "professional_review", output_summary: "核对保障缺口。" },
    { component_id: "component-no-action", purpose: "no_action", allowed_risk: "low", deterministic_tool: "no_action", status: "blocked", output_summary: "当前不新增投资。" },
  ],
  referrals: [
    {
      id: "referral-insurance",
      household_id: "household-b",
      solution_id: "solution-b",
      component_id: "component-protection",
      specialist_type: "insurance_specialist",
      trigger_reason: "保障缺口需要专业复核。",
      urgency: "high",
      status: "open",
      due_date: "2026-08-17",
      evidence: { auto_routed: true },
    },
  ],
} satisfies CFSSolutionResponse;
