import type { ClientExperience } from "../api/clientExperience";
import { knowledgeSearchFixture } from "./trustFixture";

const journey: ClientExperience["journey"] = [
  ["privacy", "隐私授权", "completed", "已有有效授权", "核对授权范围", "privacy"],
  ["quick", "快速体验", "completed", "合成家庭可直接体验", "查看家庭结论", "health"],
  ["deep", "深度规划", "ready", "确定性引擎可用", "进入家庭建档", "family"],
  ["profile", "家庭建档", "completed", "已记录 3 名家庭成员", "核对责任关系", "family"],
  ["checkup", "财务体检", "completed", "数据完整度 83%", "查看诊断", "health"],
  ["goals", "家庭目标", "completed", "已记录 3 个目标", "核对期限和冲突", "goals"],
  ["behavior", "风险与行为测评", "completed", "已有行为证据", "查看双画像", "behavior"],
  ["accounts", "四账户", "completed", "已按家庭约束动态计算", "核对三种分母", "accounts"],
  ["comparison", "方案对比", "ready", "候选方案与闸门可用", "比较方案", "accounts"],
  ["twin", "数字孪生", "ready", "可运行压力场景", "运行路径模拟", "twin"],
  ["report", "规划书", "completed", "八章预览已生成", "核对计算和引用", "report"],
  ["calendar", "行动日历", "completed", "规则行动已生成", "查看行动", "actions"],
  ["review", "持续复盘", "ready", "家庭事实变化后重算", "安排复盘", "actions"],
].map(([code, label, status, reason, action, view]) => ({ code, label, status, reason, action, view })) as ClientExperience["journey"];

const chapterTitles = [
  "家庭画像与生命周期",
  "资产负债与现金流",
  "财务健康与家庭保障",
  "家庭目标与冲突",
  "四账户动态规划",
  "方案比较与数字孪生",
  "行动日历与复盘",
  "计算依据、引用与风险边界",
];

const calendarCodes: ClientExperience["action_calendar"][number]["code"][] = [
  "immediate",
  "three_months",
  "one_year",
  "long_term",
  "next_12_months",
];

export const clientExperienceFixture: ClientExperience = {
  household_id: "household-b",
  household_code: "DEMO_B",
  household_name: "B 家庭（测试夹具）",
  household_version: 1,
  synthetic_data: true,
  analysis_date: "2026-08-04",
  data_as_of: "2025-12-31",
  journey,
  privacy: {
    active_consent_count: 1,
    withdrawn_consent_count: 0,
    consents: [{
      id: "consent-fixture",
      scopes: ["家庭财务体检", "目标规划"],
      purpose: "生成家庭财富规划",
      granted_at: "2026-08-04T00:00:00Z",
      withdrawn_at: null,
      consent_version: "consent-v1",
      record_version: 1,
      status: "active",
      withdrawal_allowed: true,
      scenario: "core_planning",
      sensitive: false,
      explicit: true,
      minimum_necessary: true,
    }],
    export_path: "/api/v1/households/household-b/privacy/exports",
    delete_path: "/api/v1/households/household-b/privacy/deletion-requests",
    deletion_mode: "logical_erasure_with_confirmation",
    human_review_path: "/api/v1/households/household-b/privacy/human-review-requests",
    boundary_note: "撤回后不再把对应范围用于新计算；Mock 数据不连接真实银行账户。",
  },
  action_calendar: calendarCodes.map((code, groupIndex) => ({
    code,
    label: ["立即处理", "未来三个月", "一年内", "长期", "未来 12 个月复盘"][groupIndex]!,
    description: "任务来自确定性规划规则。",
    items: code === "next_12_months"
      ? Array.from({ length: 12 }, (_, index) => ({
          code: `monthly_review_${String(index + 1).padStart(2, "0")}`,
          title: index === 11 ? "完成年度家庭体检" : "月度行动复盘",
          detail: "记录家庭事实变化，不自动交易或调仓。",
          why: "按固定月度节奏复核家庭事实。",
          constraint_or_formula: `分析日 + ${index + 1} 个自然月`,
          change_trigger: "家庭事实变化时重新计算。",
          risk_and_assumptions: "不自动交易或保证改善。",
          amount: "0.00",
          due_date: `2027-${String(index + 1).padStart(2, "0")}-04`,
          priority: index + 1,
          source_record_ids: [],
          calculation_source: "deterministic_review_schedule" as const,
        }))
      : [{
          code: `action-${code}`,
          title: code === "immediate" ? "补足应急储备" : "核对家庭行动",
          detail: "按目标期限与安全闸门处理。",
          why: "七步资金瀑布命中当前安全缺口。",
          constraint_or_formula: "金额直接读取 PlanningResponse.actions.amount",
          change_trigger: "收入、支出、目标或安全约束变化时重新计算。",
          risk_and_assumptions: "未经确认不执行，不代表保本或收益承诺。",
          amount: code === "immediate" ? "12000.00" : "0.00",
          due_date: "2026-08-18",
          priority: groupIndex + 1,
          source_record_ids: ["fixture-record"],
          calculation_source: "deterministic_planning_rules" as const,
        }],
  })),
  report: {
    report_version: "client-report-preview-v1.0.0",
    knowledge_retrieval_version: "hybrid-rag-v1.0.0",
    title: "B 家庭（测试夹具）家庭财富规划书",
    subtitle: "比赛版确定性预览，待顾问和合规人员复核",
    chapter_count: 8,
    chapters: chapterTitles.map((title, index) => ({
      number: index + 1,
      title,
      summary: index === 4 ? "四账户按七步资金瀑布动态生成，不使用固定比例。" : `第 ${index + 1} 章使用已确认家庭事实。`,
      calculation_basis: ["确定性规则与版本化家庭事实"],
      citation_ids: index === 7 ? ["cite:pension"] : [],
      status: index === 5 ? "pending_twin" as const : "ready" as const,
    })),
    citations: knowledgeSearchFixture.citations,
    generated_at: "2026-08-04T00:00:00Z",
    data_as_of: "2025-12-31",
    calculation_source: "deterministic_client_experience_composer",
    boundary_note: "严格保持八章；语言模型不得改写金额、比例或配置。",
  },
  delivery: {
    report: "not_generated",
    workflow: "not_created",
    actions: "not_generated",
    explanation: "尚未生成正式报告；客户端可从确定性预览创建新快照。",
  },
  calculation_versions: {
    experience: "client-experience-v1.0.0",
    financial_formula: "financial-health-v1.0.0",
    planning_rule: "1.1.0",
    knowledge_retrieval: "hybrid-rag-v1.0.0",
    report: "client-report-preview-v1.0.0",
  },
  state_catalog: [
    "loading", "skeleton", "empty", "first_use", "missing_data", "data_conflict",
    "calculation_failed", "model_degraded", "permission_denied", "offline", "stale_data",
    "no_suitable_product", "compliance_blocked", "report_failed",
  ],
  mock_mode_supported: true,
};
