import type {
  ClientProfileResponse,
  WealthNeedsResponse,
} from "../api/clientProfile";

export const clientProfileFixture: ClientProfileResponse = {
  meta: {
    household_id: "household-b",
    analysis_date: "2026-08-10",
    data_as_of: "2026-08-10",
    input_version: 4,
    source_snapshot_id: "profile-input:fixture",
    rule_version: "1.0.0",
    formula_version: "client-profile-engine-v1",
    calculation_source: "deterministic_tools",
    synthetic_data: true,
  },
  profile: {
    id: "profile-b",
    household_id: "household-b",
    profile_version: 1,
    lifecycle_stage: "parenting",
    wealth_tier: "affluent",
    service_complexity: "enhanced",
    risk_capacity: "medium",
    risk_willingness: "medium_high",
    behavior_limit: "medium",
    enterprise_dependency_level: "none",
    cross_border_complexity: "none",
    succession_complexity: "none",
    pension_stage: "accumulation",
    completeness_score: "1.000000",
    data_gaps: [],
    profile_hash: "profile-hash-fixture",
    status: "active",
    explanation: {
      household_stage: "家庭当前处于育儿成长阶段，主要规划人年龄 35。",
      income_and_career: "已识别 2 项收入来源，年化收入合计 360000.00 CNY。",
      asset_liability_features: "金融图资产 2850000.00 CNY，现有负债 1208000.00 CNY。",
      goals_and_responsibilities: "已识别 3 项目标与 2 项家庭责任。",
      risk_capacity: "风险能力为 medium，风险意愿为 medium_high。",
      behavior_risk: "行为风险上限为 medium；已记录 1 项行为观察。",
      profile_boundary: "本页是动态财富规划画像。",
    },
    currency: "CNY",
    valuation_date: "2026-08-10",
  },
  tags: [
    {
      id: "tag-private",
      tag_code: "middle_class_family",
      tag_category: "family_structure",
      confidence: "0.950000",
      severity: "info",
    },
  ],
};

export const wealthNeedsFixture: WealthNeedsResponse = {
  meta: {
    household_id: "household-b",
    profile_id: "profile-b",
    profile_hash: "profile-hash-fixture",
    analysis_date: "2026-08-10",
    data_as_of: "2026-08-10",
    rule_version: "1.0.0",
    formula_version: "client-profile-engine-v1",
    calculation_source: "deterministic_tools",
    professional_review_count: 1,
  },
  needs: [
    {
      id: "need-emergency",
      need_type: "emergency",
      target_amount: "144000.00",
      minimum_amount: "120000.00",
      currency: "CNY",
      start_date: "2026-08-10",
      end_date: "2027-08-10",
      rigidity: "rigid",
      priority: 1,
      status: "partially_prepared",
      confidence: "0.980000",
      professional_review_required: false,
      source_kind: "goal",
    },
    {
      id: "need-succession",
      need_type: "succession",
      target_amount: "1642000.00",
      minimum_amount: "0.00",
      currency: "CNY",
      start_date: "2026-08-10",
      end_date: null,
      rigidity: "important",
      priority: 2,
      status: "needs_review",
      confidence: "0.600000",
      professional_review_required: true,
      source_kind: "succession_profile",
    },
  ],
  priorities: [
    {
      wealth_need_id: "need-emergency",
      priority_rank: 1,
      hard_constraint: true,
      priority_score: "0.960000",
      reason: "家庭安全与刚性责任优先",
      rule_version: "1.0.0",
    },
    {
      wealth_need_id: "need-succession",
      priority_rank: 2,
      hard_constraint: false,
      priority_score: "0.550000",
      reason: "按目标期限、责任刚性与资料置信度排序",
      rule_version: "1.0.0",
    },
  ],
};
