import type { CompetitionDemoResponse } from "../api/competition";

export const competitionFixture = {
  demo_status: "synthetic_demo",
  bank_connection: false,
  client: {
    personal_profile: { name: "周先生（合成）", age: 38, city: "上海", occupation: "产品负责人", marital_status: "married" },
    family_profile: {
      members: [
        { relationship: "本人", age: 38, financially_dependent: false },
        { relationship: "配偶", age: 36, financially_dependent: false },
        { relationship: "子女", age: 7, financially_dependent: true },
      ],
      dependent_count: 1,
      has_minor_child: true,
      has_elder_support: true,
    },
    income_profile: { annual_income: "420000", spouse_annual_income: "230000", passive_annual_income: "0", stability_score: "0.85" },
  },
  balance_sheet: {
    total_assets: "6800000",
    financial_assets: "1800000",
    total_liabilities: "2100000",
    net_worth: "4700000",
    liquid_assets: "1300000",
    investment_assets: "1700000",
    monthly_cash_flow: "4833.33",
    debt_to_income_ratio: "0.24",
    emergency_fund_months: "4",
    asset_concentration: "0.705882",
    insurance_protection_gap: "3650000",
    accounting_identity: "6800000 - 2100000 = 4700000",
  },
  cash_flow: { annual_income: "650000", annual_expense: "436000", annual_debt_service: "156000", annual_surplus: "58000" },
  wealth_accounts: [
    { code: "liquidity", chinese_name: "要花的钱", target_amount: "143750", share_of_financial_assets: "0.079861", drivers: ["收入稳定性 0.85"], explanation: "覆盖日常支出与动态应急月数。" },
    { code: "protection", chinese_name: "保命的钱", target_amount: "39600", share_of_financial_assets: "0.022", drivers: ["保障缺口 365万元"], explanation: "保障额度与保费现金预算分开。" },
    { code: "liability_goal_matching", chinese_name: "保本与目标匹配的钱", target_amount: "300000", share_of_financial_assets: "0.166667", drivers: ["五年内目标"], explanation: "匹配近期刚性目标。" },
    { code: "growth", chinese_name: "生钱的钱", target_amount: "1316650", share_of_financial_assets: "0.731472", drivers: ["安全责任后的剩余资金"], explanation: "不使用固定40%。" },
  ],
  goals: [
    { goal_id: "G01", name: "补足家庭应急储备", future_value: "183600", projected_assets: "183600", required_monthly_saving: "2596", allocated_monthly_saving: "2596", funding_gap: "0", success_probability: "0.88", coordination_status: "on_track" },
    { goal_id: "G02", name: "子女大学教育", future_value: "2052000", projected_assets: "1100000", required_monthly_saving: "9499", allocated_monthly_saving: "2237", funding_gap: "952000", success_probability: "0.53", coordination_status: "resource_constrained" },
  ],
  risk_budget: {
    risk_capacity: "0.78",
    risk_tolerance: "0.69",
    risk_requirement: "0.52",
    effective_risk_budget: "0.69",
    maximum_portfolio_volatility: "0.143",
    maximum_cvar_loss: "0.16",
    risk_level: 4,
    binding_dimension: "tolerance",
    requirement_conflict: false,
    evidence: ["收入稳定性=0.85"],
  },
  quant: {
    input_hash: "abc",
    engine_version: "competition-quant-v1",
    selected_method: "cvar",
    selection_reason: "同一硬约束下选择尾部风险更稳健的方案。",
    methods: ["mean_variance", "risk_parity", "cvar", "black_litterman"].map((method, index) => ({
      method,
      status: "optimal",
      weights: { cash_equivalent: "0.15", fixed_income: "0.55", diversified_equity: "0.10", real_assets: "0.10", gold: "0.10" },
      metrics: { expected_return: String(0.04 + index * 0.002), volatility: "0.08", sharpe_ratio: "0.42", cvar_loss: "0.06", max_drawdown: "0.08", liquidity_score: "0.84" },
      evaluated_candidates: 420,
      binding_constraints: ["minimum_cash"],
    })),
  },
  product_pipeline: {
    stages: ["Asset Allocation", "Product Filtering", "Suitability Check", "Product Ranking", "Portfolio Construction", "Compliance Agent Approval"],
    recommendations: [{
      product: { product_id: "CFS-BOND-01", product_name: "模拟中短债基金类型", product_type: "bond_fund", asset_class: "fixed_income", risk_level: 2, fees: "0.004", is_demo: true },
      target_weight: "0.55",
      target_amount: "724157.50",
      rank_score: "0.92",
      compliance: { passed: true, violations: [], checked_rules: ["risk", "horizon", "liquidity", "concentration", "minimum", "conflict", "customer"] },
      why_selected: ["量化配置后同类筛选"],
    }],
    rejected_products: [{ product_id: "CFS-THEME-01", passed: false, violations: ["product_risk_above_customer_limit"], checked_rules: ["risk"] }],
    suitability_violation_rate: "0",
    no_executable_product: false,
  },
  behavior_findings: [{ bias: "loss_aversion", evidence: ["2024-02-05：市场下跌时快速减仓。"], risk: "可能破坏长期路径。", intervention: "设置48小时冷静期。" }],
  citations: [{ citation_id: "wealth_product_suitability", title: "理财产品适当性规则快照", source_type: "official_snapshot", source_uri: "https://example.com", excerpt: "产品与客户应分别评级并匹配。" }],
  advisor_summary: ["净资产可验证。", "量化结果不可由 Advisor 修改。"],
  rm_copilot: {
    current_wealth_issues: ["房产集中"],
    priority_goals: ["教育"],
    holding_risks: ["权益分账"],
    service_opportunities: ["保障复核", "教育金分账"],
    next_best_action: "客户经理在7日内完成三项会谈复核。",
    communication_guide: ["先谈目标"],
    human_review_items: ["自住房集中度超过60%", "保障缺口较大"],
  },
  human_escalation: { required: true, triggers: ["高资产家庭"], service_level: "priority", next_best_action: "人工复核" },
  audit: {
    engine_version: "competition-cfs-v1",
    analysis_date: "2026-09-01",
    input_hash: "input",
    output_hash: "1234567890abcdef",
    calculation_source: "deterministic_tools",
    llm_modified_quant_output: false,
    external_network_calls: 0,
    data_boundary: "synthetic_demo_not_icbc_production",
  },
} as CompetitionDemoResponse;
