import type {
  EnterpriseRecordMeta,
  FamilyEnterpriseView,
} from "../api/familyEnterprise";

const recordMeta: EnterpriseRecordMeta = {
  id: "record-id",
  currency: "CNY",
  valuation_date: "2026-08-10",
  data_source: "hero-acceptance",
  is_user_confirmed: true,
  version: 1,
  created_at: "2026-08-10T08:00:00Z",
  updated_at: "2026-08-10T08:00:00Z",
  is_deleted: false,
  deleted_at: null,
};

export const familyEnterpriseFixture: FamilyEnterpriseView = {
  meta: {
    household_id: "household-b",
    analysis_date: "2026-08-10",
    data_as_of: "2026-08-10",
    input_hash: "enterprise-input-hash-123456789",
    rule_version: "1.0.0",
    formula_version: "family-enterprise-dependency-v1",
    calculation_source: "deterministic_tools",
  },
  enterprises: [
    {
      profile: {
        ...recordMeta,
        id: "enterprise-1",
        household_id: "household-b",
        name: "景行智造科技",
        industry: "高端制造",
        stage: "mature",
        jurisdiction: "CN",
        listed_status: "unlisted",
        enterprise_type: "operating_company",
      },
      latest_valuation: {
        ...recordMeta,
        id: "valuation-1",
        household_id: "household-b",
        enterprise_id: "enterprise-1",
        equity_value: "17000000.00",
        valuation_method: "user_estimate",
        confidence: "medium",
        source_kind: "client_financial_statement",
        evidence: {},
      },
      ownerships: [{
        ...recordMeta,
        id: "ownership-1",
        household_id: "household-b",
        enterprise_id: "enterprise-1",
        owner_entity_id: "person-1",
        ownership_ratio: "1.000000",
        voting_ratio: "1.000000",
        instrument_type: "common_equity",
        vesting_date: null,
        lockup_end_date: null,
      }],
      cashflows: [
        {
          ...recordMeta,
          id: "cashflow-1",
          household_id: "household-b",
          enterprise_id: "enterprise-1",
          member_id: null,
          cashflow_type: "salary",
          amount: "360000.00",
          frequency: "annual",
          stability: "medium",
        },
        {
          ...recordMeta,
          id: "cashflow-2",
          household_id: "household-b",
          enterprise_id: "enterprise-1",
          member_id: null,
          cashflow_type: "dividend",
          amount: "240000.00",
          frequency: "annual",
          stability: "low",
        },
      ],
      guarantees: [{
        ...recordMeta,
        id: "guarantee-1",
        household_id: "household-b",
        enterprise_id: "enterprise-1",
        member_id: null,
        guarantee_type: "personal",
        guaranteed_amount: "5000000.00",
        outstanding_exposure: "5000000.00",
        expiry_date: "2029-12-31",
      }],
      liquidity_events: [{
        ...recordMeta,
        id: "event-1",
        household_id: "household-b",
        enterprise_id: "enterprise-1",
        event_type: "ipo",
        expected_date: "2028-06-30",
        estimated_value: "17000000.00",
        probability: "0.350000",
        lockup: true,
        status: "planned",
      }],
      household_owned_value: "17000000.00",
    },
  ],
  wealth: {
    household_wealth: "8000000.00",
    financial_assets: "3000000.00",
    property_assets: "5000000.00",
    enterprise_wealth: "17000000.00",
    economic_household_wealth: "25000000.00",
    enterprise_wealth_ratio: "0.680000",
  },
  income: {
    enterprise_annual_income: "600000.00",
    household_annual_income: "360000.00",
    dependency_ratio: "1.000000",
    low_stability_annual_income: "240000.00",
  },
  guarantees: {
    guaranteed_amount: "5000000.00",
    outstanding_exposure: "5000000.00",
    active_count: 1,
  },
  dependency: {
    components: [
      { code: "wealth_dependency", label: "财富依赖", ratio: "0.680000", weighted_score: "0.272000", numerator: "17000000.00", denominator: "25000000.00", explanation: "企业权益占家庭经济财富的比例。" },
      { code: "income_dependency", label: "收入依赖", ratio: "1.000000", weighted_score: "0.350000", numerator: "600000.00", denominator: "600000.00", explanation: "工资、分红和经营分配对同一企业来源的依赖。" },
      { code: "guarantee_dependency", label: "担保依赖", ratio: "0.200000", weighted_score: "0.030000", numerator: "5000000.00", denominator: "25000000.00", explanation: "家庭为企业承担的未偿担保暴露。" },
      { code: "pledge_dependency", label: "质押依赖", ratio: "0.000000", weighted_score: "0.000000", numerator: "0.00", denominator: "3000000.00", explanation: "与企业相关且已质押的持仓暴露。" },
      { code: "currency_dependency", label: "币种依赖", ratio: "0.000000", weighted_score: "0.000000", numerator: "0.00", denominator: "17000000.00", explanation: "当前不伪造实时汇率。" },
    ],
    score: "0.652000",
    level: "high",
    label: "高 Enterprise Dependency",
    regulatory_rating: false,
    disclaimer: "该分数只用于家庭财富规划中的暴露识别，不是监管评级、征信评分或企业估值结论。",
  },
  economic_capital: {
    unlisted_company_equity: "17000000.00",
    listed_employer_stock: "0.00",
    equity_incentives: "0.00",
    liquid_securities_equity: "0.00",
    enterprise_salary_and_dividend_dependency: "600000.00",
    guarantee_exposure: "5000000.00",
    pledge_exposure: "0.00",
    total_economic_equity_exposure: "17000000.00",
    economic_equity_ratio: "0.680000",
    risk_budget_ceiling_ratio: "0.500000",
    risk_budget_ceiling_amount: "12500000.00",
    remaining_incremental_equity_capacity: "0.00",
    additional_equity_risk_allowed: false,
    explanation: "经济权益暴露同时纳入非上市股权、雇主股、股权激励和证券账户权益。证券账户持股低不代表家庭权益风险低。",
  },
  liquidity_events: [{
    ...recordMeta,
    id: "event-1",
    household_id: "household-b",
    enterprise_id: "enterprise-1",
    event_type: "ipo",
    expected_date: "2028-06-30",
    estimated_value: "17000000.00",
    probability: "0.350000",
    lockup: true,
    status: "planned",
  }],
  cfs_implication: {
    status: "constraints_available",
    constraints: [
      "企业依赖度高，不应因证券账户持股低而机械增加权益风险。",
      "先审查创始人担保的追偿边界、期限与风险隔离。",
      "预期流动性事件仍受限售期约束，不将估值当作可用现金。",
    ],
    explanation: "E06 才会组装 CFS；E05 只输出必须传递给 CFS 的家企风险约束，不提前生成产品或方案。",
  },
};
