import type { FinancialAnalysis, MetricResult } from "../api/financial";

function metric(
  metricId: string,
  name: string,
  result: string,
  unit: string,
  formula: string,
  substitution: string,
): MetricResult {
  return {
    metric_id: metricId,
    name,
    formula,
    substitution,
    inputs: [
      {
        key: "fixture_input",
        label: "测试输入",
        value: result,
        unit,
        source_record_ids: ["fixture-record"],
      },
    ],
    result,
    numerator: result,
    denominator: unit === "CNY" ? null : "1",
    unit,
    threshold_version: "financial_health@1.0.0",
    status: "attention",
    explanation_key: `metric.${metricId}.attention`,
    data_as_of: "2025-12-31",
    source_type: "deterministic_derived",
    applicability: { applicable: true, reason: "测试家庭具备所需字段" },
    reference: {
      reference_range: "内部演示参考条件",
      source_type: "internal_demo",
      source_reference: "仅用于验证界面，不构成建议",
      parameters: {},
    },
    explanation: "该结果由测试夹具模拟确定性 API 返回。",
    actions: ["核对源记录与口径。"],
  };
}

export const financialFixture: FinancialAnalysis = {
  meta: {
    household_id: "household-b",
    household_code: "DEMO_B",
    analysis_date: "2026-08-04",
    data_as_of: "2025-12-31",
    input_version: "fixture-input",
    formula_version: "financial-metrics-v1.0.0",
    rule_code: "financial_health",
    rule_version: "1.0.0",
    calculation_source: "deterministic_tools",
    currency: "CNY",
    synthetic_data: true,
  },
  profile: {
    name: "B 家庭（测试夹具）",
    lifecycle_stage: "family_growth",
    region: "上海",
    members: [],
    data_source: "synthetic_fixture",
    is_user_confirmed: false,
  },
  statements: {
    balance_sheet: {
      assets: [
        {
          id: "asset-home",
          name: "自住房",
          category: "residential_property",
          subcategory: null,
          asset_group: "property",
          market_value: "2400000",
          acquisition_cost: "1800000",
          unrealized_change: "600000",
          liquidity_days: 180,
          liquidity_level: "illiquid",
          property_use: "self_use",
          pledged: true,
          valuation_date: "2025-12-31",
        },
      ],
      liabilities: [
        {
          id: "liability-mortgage",
          name: "住房按揭",
          category: "mortgage",
          outstanding_balance: "1200000",
          annual_interest_rate: "0.035",
          monthly_payment: "6000",
          scheduled_twelve_month_payment: "72000",
          maturity_date: "2045-01-01",
          rate_type: "floating",
          linked_asset_id: "asset-home",
          is_high_interest: false,
        },
      ],
      asset_totals_by_group: { property: "2400000", financial: "450000" },
      liability_totals_by_category: { mortgage: "1200000", credit_card: "8000" },
      total_assets: "2850000",
      total_liabilities: "1208000",
      net_worth: "1642000",
      accounting_identity: "资产 2,850,000 - 负债 1,208,000 = 净资产 1,642,000",
    },
    cash_flow: {
      income_lines: [],
      expense_lines: [],
      income_totals_by_type: { employment: "360000" },
      expense_totals_by_category: { living: "288000" },
      annual_income: "360000",
      annual_expenses: "288000",
      annual_surplus: "72000",
      annual_basic_living_expenses: "144000",
      annual_essential_expenses: "240000",
      annual_fixed_expenses: "228000",
      annual_debt_service: "72000",
      annual_insurance_premiums: "12000",
    },
    insurance: {
      policies: [],
      coverage_by_policy_type: { term_life: "1000000" },
      total_annual_premium: "12000",
      total_cash_value: "0",
      counting_note: "保障额度不计入资产；现金价值仅在另有资产记录时计入资产。",
    },
    goal_funding: {
      goals: [],
      total_target_amount: "2900000",
      total_prepared_amount: "130000",
      total_funding_gap: "2770000",
    },
    liquidity: {
      lines: [],
      totals_by_tier: { immediate: "50000", short_term: "32000" },
      emergency_liquid_assets: "50000",
      short_term_liquid_assets: "320000",
      twelve_month_liquid_assets: "320000",
    },
  },
  metrics: [
    metric("net_worth", "净资产", "1642000", "CNY", "总资产 - 总负债", "2,850,000 - 1,208,000 = 1,642,000"),
    metric("liquidity_reserve_months", "应急储备月数", "4.17", "months", "应急流动资产 / 月基本生活支出", "50,000 / 12,000 = 4.17"),
    metric("debt_to_asset_ratio", "资产负债率", "0.423860", "ratio", "总负债 / 总资产", "1,208,000 / 2,850,000 = 0.423860"),
    metric("savings_ratio", "结余比率", "0.200000", "ratio", "年结余 / 年收入", "72,000 / 360,000 = 0.200000"),
  ],
  diagnostics: {
    completeness_score: "83",
    passed_checks: 7,
    issue_count: 1,
    issues: [
      {
        code: "debt_service_reconciliation",
        severity: "attention",
        title: "债务偿付口径需要复核",
        detail: "现金流记录与未来十二月计划偿付存在差异。",
        related_record_ids: ["liability-mortgage"],
        action: "核对信用卡待还款和按揭计划。",
      },
    ],
  },
  protection: {
    risks: [
      {
        risk_code: "family_responsibility",
        name: "家庭责任",
        required_amount: "2452000",
        existing_coverage: "1000000",
        coverage_ratio: "0.407830",
        gap: "1452000",
        priority: 1,
        basis: "负债、刚性目标与家庭过渡期支出",
      },
    ],
    most_significant_risk: "家庭责任",
    coverage_ratio: "0.407830",
    protection_gap: "1452000",
    annual_premium: "12000",
    premium_to_income_ratio: "0.033333",
    payment_pressure: "manageable",
    counting_note: "各风险场景分别测算，不跨场景叠加为产品保额。",
  },
  purchasing_power: {
    official_cpi: {
      code: "official_cpi",
      name: "CPI 离线演示参数",
      rate: "0.02",
      source_type: "internal_demo",
      source_reference: "离线演示参数，非实时统计数据",
      data_as_of: "2025-12-31",
      note: "上线时需接入权威数据并展示发布日期。",
    },
    family_weighted_inflation: {
      code: "family_weighted_inflation",
      name: "家庭加权生活成本增速",
      rate: "0.017292",
      source_type: "internal_demo",
      source_reference: "家庭支出分类权重与演示分类参数",
      data_as_of: "2025-12-31",
      note: "不是官方 CPI。",
    },
    goal_specific_cost_growth: [],
    minimum_wage_catch_up: {
      code: "minimum_wage_catch_up",
      name: "最低工资追赶参数",
      rate: "0.03",
      source_type: "internal_demo",
      source_reference: "情景参数",
      data_as_of: "2025-12-31",
      note: "不等同于 CPI 或收益保证。",
    },
    minimum_wage_is_cpi: false,
    minimum_wage_is_return_guarantee: false,
  },
  health_dimensions: [
    { code: "liquidity", name: "流动性健康", score: "69", metric_ids: ["liquidity_reserve_months"], explanation: "归一化展示", weight: "0.1", available: true, is_regulatory_rating: false },
    { code: "balance_sheet", name: "资产负债健康", score: "58", metric_ids: ["debt_to_asset_ratio"], explanation: "归一化展示", weight: "0.1", available: true, is_regulatory_rating: false },
    { code: "protection", name: "风险保障", score: "42", metric_ids: ["protection_coverage_ratio"], explanation: "归一化展示", weight: "0.1", available: true, is_regulatory_rating: false },
    { code: "retirement", name: "养老准备", score: "28", metric_ids: ["retirement_funding_adequacy"], explanation: "归一化展示", weight: "0.1", available: true, is_regulatory_rating: false },
    { code: "goals", name: "目标健康", score: "34", metric_ids: ["goal_funding_ratio"], explanation: "归一化展示", weight: "0.1", available: true, is_regulatory_rating: false },
    { code: "portfolio_risk", name: "组合风险", score: "51", metric_ids: ["product_hhi"], explanation: "归一化展示", weight: "0.1", available: true, is_regulatory_rating: false },
    { code: "concentration", name: "集中度", score: "36", metric_ids: ["product_hhi"], explanation: "归一化展示", weight: "0.1", available: true, is_regulatory_rating: false },
    { code: "long_term_growth", name: "长期增长", score: "50", metric_ids: ["savings_ratio"], explanation: "归一化展示", weight: "0.1", available: true, is_regulatory_rating: false },
    { code: "behavior", name: "行为稳定", score: "54", metric_ids: ["behavior_assessment"], explanation: "归一化展示", weight: "0.1", available: true, is_regulatory_rating: false },
    { code: "resilience", name: "财务韧性", score: "61", metric_ids: ["liquidity_reserve_months"], explanation: "归一化展示", weight: "0.1", available: true, is_regulatory_rating: false },
  ],
  health_assessment: {
    code: "chfi",
    version: "chfi-demo-v1.0.0",
    overall_score: "46.37",
    status: "risk",
    formula: "100 × 十维得分的等权几何平均",
    weighting_note: "初赛采用可用维度等权几何平均，后续需用脱敏样本校准。",
    hard_gate_triggered: true,
    hard_gates: [
      { code: "one_month_liquidity", name: "一个月必要支出来源", status: "pass", detail: "已通过", metric_ids: ["liquidity_reserve_months"] },
      { code: "debt_service_pressure", name: "偿债现金流压力", status: "pass", detail: "已通过", metric_ids: ["debt_service_burden_ratio"] },
      { code: "protection_gap", name: "重大风险保障缺口", status: "risk", detail: "需处理", metric_ids: ["protection_coverage_ratio"] },
    ],
    priority_action: {
      dimension_code: "protection",
      title: "先补关键保障缺口",
      detail: "保险只承担风险转移，不承担投资任务；先核对家庭经济支柱的医疗、重疾和意外保障。",
      metric_ids: ["protection_coverage_ratio", "protection_gap"],
    },
    is_credit_score: false,
    is_regulatory_rating: false,
  },
};
