import type { FundAdvisoryResponse } from "../api/fundAdvisory";

const evidence = {
  evidence_id: "icbc_482002_cash_service",
  title: "工银货币业务简介",
  issuer: "中国工商银行",
  url: "https://www.sh.icbc.com.cn/ningbo/column/1438058341816746087.html",
  published_or_as_of: null,
  verified_on: "2026-08-07",
  supports: ["product_identity", "fund_terms", "icbc_public_listing"],
  note: "工行页面明确记录基金代码和渠道。",
};

const product = {
  code: "482002",
  name: "工银瑞信货币市场基金A类基金份额",
  short_name: "工银货币",
  manager: "工银瑞信基金管理有限公司",
  share_class: "A",
  category: "money_market",
  trade_venue: "off_exchange" as const,
  tracked_index: null,
  broad_index: false,
  sector_or_thematic: false as const,
  leveraged: false as const,
  inverse: false as const,
  qdii: false,
  internal_risk_level: "r1" as const,
  minimum_holding_days: 0,
  normal_redemption_note: "以工行当日页面为准。",
  eligible_sleeves: ["daily_liquidity" as const, "stable_capital" as const],
  personal_pension_eligible: false,
  icbc_publicly_listed: true,
  icbc_channel_status: "official_public_listing_app_confirmation_required" as const,
  icbc_channel_note: "工行公开列示，交易当日仍需确认。",
  principal_guaranteed: false as const,
  selection_priority: 10,
  evidence: [evidence],
};

export const fundAdvisoryFixture: FundAdvisoryResponse = {
  meta: {
    household_id: "household-b",
    household_code: "DEMO_B",
    analysis_date: "2026-08-07",
    data_as_of: "2026-08-04",
    input_version: "fund-advisory-input-fixture",
    engine_version: "fund_advisory_engine_v1.0.0",
    catalog_version: "1.0.0",
    catalog_data_date: "2026-06-30",
    catalog_stale: false,
    icbc_only: true,
    calculation_source: "deterministic_tools",
    currency: "CNY",
    synthetic_data: true,
  },
  effective_customer_risk: "medium_low",
  family_safety_status: "block",
  sleeves: [
    {
      sleeve_code: "daily_liquidity",
      name: "要花的钱",
      source_amount: "100000.00",
      status: "recommended",
      objective: "保留支付流动性",
      allocations: [
        {
          allocation_type: "fund",
          ratio: "1.00",
          amount: "100000.00",
          product_code: "482002",
          product_name: product.name,
          product_risk_level: "r1",
          icbc_publicly_listed: true,
          purchase_route: "工行手机银行搜索六位代码 482002，以当日页面为准",
          reasons: ["真实代码已核验。"],
          warnings: ["基金不保本不保收益。"],
          evidence_urls: [evidence.url],
        },
      ],
      candidate_products: [],
      guardrails: ["不以基金替代全部支付现金。"],
      explanation: "测试建议。",
    },
    ...(["stable_capital", "long_term_growth"] as const).map((sleeveCode) => ({
      sleeve_code: sleeveCode,
      name: sleeveCode === "stable_capital" ? "保本的钱" : "生钱的钱",
      source_amount: "0.00",
      status: "not_applicable" as const,
      objective: "当前暂无金额",
      allocations: [],
      candidate_products: [],
      guardrails: ["不绕过安全闸门。"],
      explanation: "当前暂无可配置金额。",
    })),
    {
      sleeve_code: "personal_pension",
      name: "个人养老金投资",
      source_amount: "30000.00",
      status: "channel_verification_required",
      objective: "名录和渠道双重核验",
      allocations: [
        {
          allocation_type: "unallocated_guardrail",
          ratio: "1.00",
          amount: "30000.00",
          product_code: null,
          product_name: null,
          product_risk_level: null,
          icbc_publicly_listed: null,
          purchase_route: "保留原账户，核验后再执行",
          reasons: ["工行渠道尚未核验。"],
          warnings: ["不为满仓放宽证据。"],
          evidence_urls: [],
        },
      ],
      candidate_products: [
        {
          product_code: "020189",
          product_name: "建信添福悠享稳健养老目标一年持有期债券型基金中基金（FOF）Y类基金份额",
          role: "官方名录内的个人养老金债券型FOF",
          status: "channel_verification_required",
          reason: "尚未核验工行当前货架。",
        },
      ],
      guardrails: ["必须命中证监会最新名录。"],
      explanation: "未核验工行渠道，不直接分配。",
    },
  ],
  catalog: {
    catalog_code: "mainland_verified_fund_advisory",
    catalog_version: "1.0.0",
    data_date: "2026-06-30",
    verified_on: "2026-08-07",
    source_type: "verified_real_public_funds",
    catalog_stale: false,
    scope: "中国大陆公开募集证券投资基金。",
    mandatory_channel_notice: "工行官网公开列示不等于当前账户一定可申购。",
    personal_pension_catalog_observation: "官方目录中没有货币基金，债券型FOF候选为020189。",
    product_count: 1,
    products: [product],
  },
  hard_boundaries: ["不推荐个股、行业主题、杠杆或反向产品。"],
  execution_checklist: ["执行当日按六位代码核对基金全称。"],
  disclaimer: "本结果不是收益承诺或实时交易指令。",
};
