import type {
  EligibleCapitalResponse,
  LiabilityCalendarResponse,
} from "../api/liability";

const baseStream = {
  household_id: "household-b",
  wealth_need_id: "need-education",
  source_responsibility_id: null,
  beneficiary_entity_id: "entity-b",
  currency: "CNY",
  frequency: "annual" as const,
  minimum_amount: "250000.00",
  annual_growth_assumption: "0.000000",
  rigidity: "rigid" as const,
  deferrable: false,
  funding_sources: [],
  fallback_action: "补足资金缺口或升级人工复核",
  stream_version: "stream-fixture-v1",
  version: 1,
};

export const liabilityCalendarFixture: LiabilityCalendarResponse = {
  meta: {
    household_id: "household-b",
    analysis_date: "2026-08-10",
    data_as_of: "2026-08-10",
    rule_version: "1.0.0",
    formula_version: "eltc-purchasing-power-v2.0.0",
    calculation_source: "deterministic_tools",
    adapter_sources: ["financial_goals", "responsibilities"],
  },
  summary: {
    stream_count: 2,
    cashflow_count: 5,
    target_total: "1300000.00",
    minimum_total: "1200000.00",
    prepared_total: "200000.00",
    funding_gap: "1100000.00",
    next_due_date: "2029-03-01",
  },
  entries: [
    {
      stream: {
        ...baseStream,
        id: "stream-medical",
        source_goal_id: null,
        source_responsibility_id: "responsibility-medical",
        name: "老人医疗责任",
        stream_type: "medical",
        start_date: "2029-03-01",
        end_date: "2029-03-01",
        frequency: "one_time",
        base_amount: "300000.00",
        minimum_amount: "200000.00",
        inflation_index_code: "GCI_MEDICAL",
      },
      cashflows: [
        {
          id: "cashflow-medical",
          liability_stream_id: "stream-medical",
          due_date: "2029-03-01",
          target_amount: "300000.00",
          minimum_amount: "200000.00",
          sequence: 1,
          calculation_version: "v2-fixture",
        },
      ],
      target_total: "300000.00",
      minimum_total: "200000.00",
      prepared_amount: "0.00",
      funding_gap: "300000.00",
    },
    {
      stream: {
        ...baseStream,
        id: "stream-education",
        source_goal_id: "goal-education",
        name: "子女大学教育",
        stream_type: "education",
        start_date: "2035-09-01",
        end_date: "2038-09-01",
        base_amount: "250000.00",
        inflation_index_code: "GCI_EDUCATION",
      },
      cashflows: [2035, 2036, 2037, 2038].map((year, index) => ({
        id: `cashflow-education-${year}`,
        liability_stream_id: "stream-education",
        due_date: `${year}-09-01`,
        target_amount: "250000.00",
        minimum_amount: "250000.00",
        sequence: index + 1,
        calculation_version: "v2-fixture",
      })),
      target_total: "1000000.00",
      minimum_total: "1000000.00",
      prepared_amount: "200000.00",
      funding_gap: "800000.00",
    },
  ],
};

const bridgeRows: Array<[string, string, string, string, string, string]> = [
  ["operating_liquidity", "经营性流动资金", "1000000.00", "20000.00", "980000.00", "0.00"],
  ["emergency_reserve", "应急储备", "980000.00", "120000.00", "860000.00", "0.00"],
  ["high_interest_debt_repair", "高息债务修复", "860000.00", "0.00", "860000.00", "0.00"],
  ["protection_funding", "保障资金", "860000.00", "10000.00", "850000.00", "0.00"],
  ["short_term_hard_liabilities", "短期刚性责任", "850000.00", "650000.00", "200000.00", "0.00"],
  ["committed_goal_capital", "已承诺目标资本", "200000.00", "200000.00", "0.00", "0.00"],
  ["locked_institutional_assets", "锁定制度资产", "0.00", "30000.00", "0.00", "30000.00"],
];

export const eligibleCapitalFixture: EligibleCapitalResponse = {
  meta: {
    household_id: "household-b",
    analysis_date: "2026-08-10",
    data_as_of: "2026-08-10",
    input_hash: "eltc-input-fixture",
    rule_version: "1.0.0",
    formula_version: "eltc-purchasing-power-v2.0.0",
    calibration_version: "china-purchasing-power-calibration-v1.0.0",
    calculation_source: "deterministic_tools",
  },
  calculation: {
    dispatchable_financial_resources: "1000000.00",
    bridge: bridgeRows.map(([code, label, before, deduction, after, unfunded]) => ({
      code,
      label,
      before,
      requested_deduction: deduction,
      deduction: before === "0.00" ? "0.00" : deduction,
      after,
      unfunded,
      source: "家庭事实与责任日历",
      reason: `${label}优先于长期配置。`,
    })),
    eligible_long_term_capital: "0.00",
    eligibility_gates: [
      { code: "eltc_positive", label: "长期可配置资本为正", passed: false, reason: "前置责任已耗尽可调度金融资源。" },
      { code: "suitability", label: "适当性资料有效", passed: true, reason: "风险承担能力满足政策。" },
      { code: "high_interest_debt", label: "无待修复高息债务", passed: true, reason: "未发现高息债务。" },
      { code: "cashflow_safety", label: "可持续收入覆盖年度支出", passed: true, reason: "可持续收入不低于年度支出。" },
    ],
    formally_eligible: false,
    decision: "repair_first",
    growth_entry_threshold: {
      amount: "560000.00",
      currency: "CNY",
      source: "regional-growth-threshold-v1.0.0",
      deprecated_as_hard_gate: true,
      determines_eligibility: false,
      communication_note: "V5 中仅作为客户沟通与偏好参考，不决定投资资格。",
    },
    purchasing_power: {
      formula_version: "eltc-purchasing-power-v2.0.0",
      calibration_registry_version: "china-purchasing-power-calibration-v1.0.0",
      calibration_status: "degraded",
      calibration_modes: ["empirically_calibrated", "controlled_demo"],
      parameter_references: [],
      requires_human_review: true,
      household_cost_inflation: {
        code: "HCI",
        annual_rate: "0.028000",
        calibration_status: "degraded",
        calibration_modes: ["empirically_calibrated", "controlled_demo"],
        parameter_references: [],
        interpretation: "按家庭实际支出权重计算生活成本通胀。",
      },
      goal_cost_inflation: [
        {
          code: "GCI",
          stream_id: "stream-education",
          stream_name: "子女大学教育",
          stream_type: "education",
          inflation_index_code: "GCI_EDUCATION",
          annual_rate: "0.050000",
          calibration_status: "degraded",
          calibration_modes: ["controlled_demo"],
          parameter_references: [],
          interpretation: "目标成本增长只作用于该目标现金流。",
        },
      ],
      income_adequacy: {
        code: "IAI",
        sustainable_annual_income: "360000.00",
        essential_annual_cost: "240000.00",
        ratio: "1.500000",
        status: "comfortable",
        minimum_wage_trend: "0.030000",
        minimum_wage_scope: "income_adequacy_only",
        minimum_wage_used_as_portfolio_hurdle: false,
        calibration_status: "degraded",
        calibration_modes: ["empirically_calibrated", "controlled_demo"],
        parameter_references: [],
        interpretation: "最低工资趋势只辅助观察收入追赶能力。",
      },
      minimum_wage_used_as_cpi_proxy: false,
      minimum_wage_used_as_return_hurdle: false,
    },
  },
};
