import type {
  AccountAllocation,
  PlanningResponse,
  RatioMeasure,
  WaterfallStep,
} from "../api/planning";

function measures(amount: string): RatioMeasure[] {
  return [
    {
      denominator_id: "total_household_assets",
      denominator_name: "家庭总资产",
      denominator_value: "2850000.00",
      ratio: (Number(amount) / 2_850_000).toFixed(6),
      applicable: true,
      reason: `${amount} ÷ 2850000.00`,
      deprecated: false,
    },
    {
      denominator_id: "total_assets",
      denominator_name: "家庭总资产",
      denominator_value: "2850000.00",
      ratio: (Number(amount) / 2_850_000).toFixed(6),
      applicable: true,
      reason: `${amount} ÷ 2850000.00`,
      deprecated: true,
    },
    {
      denominator_id: "investable_financial_assets",
      denominator_name: "可投资金融资产",
      denominator_value: "320000.00",
      ratio: (Number(amount) / 320_000).toFixed(6),
      applicable: true,
      reason: `${amount} ÷ 320000.00`,
      deprecated: false,
    },
    {
      denominator_id: "residual_long_term_plannable_capital",
      denominator_name: "长期可规划资源",
      denominator_value: "396000.00",
      ratio: (Number(amount) / 396_000).toFixed(6),
      applicable: true,
      reason: `${amount} ÷ 396000.00`,
      deprecated: false,
    },
    {
      denominator_id: "annual_new_surplus",
      denominator_name: "年度新增结余",
      denominator_value: "72000.00",
      ratio: (Number(amount) / 72_000).toFixed(6),
      applicable: true,
      reason: `${amount} ÷ 72000.00`,
      deprecated: true,
    },
  ];
}

function account(
  sequence: number,
  bucket: AccountAllocation["bucket"],
  name: string,
  current: string,
  target: string,
  recommended: string,
  gap: string,
): AccountAllocation {
  return {
    bucket,
    name,
    methodology_domain: {
      daily_liquidity: "DAILY_LIQUIDITY",
      risk_protection: "RISK_PROTECTION",
      stable_goals: "STABILITY_AND_GOALS",
      long_term_growth: "LONG_TERM_GROWTH",
    }[bucket] as AccountAllocation["methodology_domain"],
    sequence,
    current_amount: current,
    target_amount: target,
    recommended_amount: recommended,
    recommended_range_min: recommended,
    recommended_range_max: target,
    gap_amount: gap,
    annual_cost_amount: bucket === "risk_protection" ? "12000.00" : "0.00",
    coverage_gap_amount: bucket === "risk_protection" ? "1452000.00" : "0.00",
    primary_denominator_name: "可投资金融资产",
    primary_denominator_id: bucket === "long_term_growth" ? "residual_long_term_plannable_capital" : "investable_financial_assets",
    reference_band:
      bucket === "stable_goals"
        ? {
            denominator_id: "investable_financial_assets",
            denominator_name: "可投资金融资产",
            minimum_ratio: "0.100000",
            maximum_ratio: "0.200000",
            target_ratio: "0.150000",
            overall_minimum_ratio: "0.050000",
            overall_maximum_ratio: "0.300000",
            market_regime: "neutral",
            market_regime_label: "中性",
            binding: false,
            conditions: ["无明确近期目标缺口时参考"],
            explanation: "中性口径为 10%—20%，全周期 5%—30% 不是固定比例。",
          }
        : null,
    current_measures: measures(current),
    target_measures: measures(target),
    measures: measures(recommended),
    formula: "按七步顺序计算，再应用五硬一软约束",
    substitution: `${current} → ${recommended}`,
    rationale: "根据家庭目标、期限和安全闸门动态生成。",
    constraint_ids: ["liquidity"],
    source_record_ids: ["fixture-record"],
    product_education: [
      bucket === "daily_liquidity"
        ? "信用卡额度不是资产，不计入日用资金。"
        : "产品风险、期限和流动性需逐项评估。",
    ],
  };
}

const stepNames = [
  "高息债务处理",
  "日常资金",
  "应急储备",
  "必要保障成本",
  "一年内确定支出",
  "一至五年刚性目标",
  "剩余长期资金",
];

const waterfallSteps: WaterfallStep[] = stepNames.map((name, index) => ({
  sequence: index + 1,
  step_code: `step-${index + 1}`,
  name,
  required_amount: index === 0 ? "8000.00" : "12000.00",
  allocated_amount: index === 6 ? "0.00" : "12000.00",
  remaining_resources: "0.00",
  status: index === 5 ? "partial" : "covered",
  formula: "顺序分配",
  explanation: "前一层完成后才进入下一层。",
  source_record_ids: ["fixture-record"],
}));

export const planningFixture: PlanningResponse = {
  meta: {
    household_id: "household-b",
    household_code: "DEMO_B",
    analysis_date: "2026-08-04",
    data_as_of: "2025-12-31",
    input_version: "fixture-planning-input",
    formula_version: "fortune-copilot-four-account-v2.2.0",
    rule_code: "dynamic_account_waterfall",
    rule_version: "2.2.0",
    rule_source_type: "internal_demo",
    calculation_source: "deterministic_tools",
    currency: "CNY",
    synthetic_data: true,
    scenario_type: "base",
    methodology_version: "3.1.0",
    regional_parameter_version: "regional-growth-threshold-v1.0.0",
    market_regime_version: "market-regime-demo-2026-08-04",
    minimum_wage_snapshot_version: "minimum-wage-demo-v1.0.0",
    pension_policy_version: "personal-pension-policy-v1.0.0",
  },
  lifecycle: {
    detected_stage: "parenting",
    recorded_stage: "parenting",
    effective_stage: "parenting",
    override_applied: false,
    dynamic_safety_months: "7.00",
    base_safety_months: "5.00",
    formula: "基础月数 + 家庭责任修正",
    substitution: "5 - 0.5 - 0.5 + 1 + 1 + 1 = 7",
    explanation: "家庭存在未成年子女。",
    evidence: [],
  },
  goals: [
    {
      goal_id: "goal-education",
      name: "子女教育",
      goal_type: "education",
      target_date: "2036-08-04",
      adjusted_target_date: "2036-08-04",
      months_remaining: 120,
      current_cost: "600000.00",
      future_amount: "988205.70",
      present_value: "809209.10",
      minimum_present_value: "606906.82",
      prepared_amount: "80000.00",
      funding_gap: "729209.10",
      minimum_funding_gap: "526906.82",
      monthly_required: "6076.74",
      annual_required: "72920.88",
      priority: 1,
      rigidity: "rigid",
      can_defer: false,
      annual_cost_growth_rate: "0.050000",
      status: "conflict",
      formula: "未来金额和现值分别复利计算",
      substitution: "未来 988,205.70；现值 809,209.10；(809,209.10 − 80,000.00) ÷ 120 = 6,076.74/月",
      source_record_ids: ["goal-education"],
    },
    {
      goal_id: "goal-retirement",
      name: "夫妻退休养老",
      goal_type: "retirement",
      target_date: "2051-05-20",
      adjusted_target_date: "2051-05-20",
      months_remaining: 298,
      current_cost: "2000000.00",
      future_amount: "4208967.97",
      present_value: "2562451.05",
      minimum_present_value: "1921838.29",
      prepared_amount: "30000.00",
      funding_gap: "2532451.05",
      minimum_funding_gap: "1891838.29",
      monthly_required: "8498.16",
      annual_required: "101977.92",
      priority: 2,
      rigidity: "important",
      can_defer: true,
      annual_cost_growth_rate: "0.030000",
      status: "conflict",
      formula: "未来金额和现值分别复利计算",
      substitution: "2562451.05 - 30000.00 = 2532451.05",
      source_record_ids: ["goal-retirement"],
    },
  ],
  conflicts: [
    {
      conflict_id: "monthly_goal_capacity",
      severity: "warning",
      title: "目标月投入超过当前新增结余",
      detail: "全部目标需求超过每月可持续结余。",
      affected_goal_ids: ["goal-education", "goal-retirement"],
      available_monthly_surplus: "6000.00",
      required_monthly_contribution: "13640.79",
      monthly_shortfall: "7640.79",
      adjustments: [
        {
          action_code: "defer_goal",
          title: "评估退休目标延期 12 个月",
          detail: "延期后月投入下降，但不隐藏目标缺口。",
          affected_goal_ids: ["goal-retirement"],
          monthly_effect: "330.00",
          preserves_minimum: true,
        },
      ],
    },
  ],
  denominators: {
    total_assets: "2850000.00",
    total_household_assets: "2850000.00",
    investable_financial_assets: "320000.00",
    net_financial_assets_after_debt: "-858600.00",
    plannable_financial_net_worth: "-858600.00",
    growth_entry_threshold: "500000.00",
    residual_long_term_plannable_capital: "0.00",
    annual_new_surplus: "72000.00",
    available_planning_resources: "404000.00",
    high_interest_debt_before_plan: "8000.00",
    high_interest_debt_after_counterfactual: "8000.00",
    same_period_cashflow_committed: "0.00",
  },
  waterfall_steps: waterfallSteps,
  constraints: [
    {
      constraint_id: "liquidity",
      constraint_type: "hard",
      name: "流动性约束",
      status: "block",
      observed_value: "当前日用与即时资产 50,000.00",
      required_condition: "达到动态日用目标 133,000.00",
      effect: "阻止把尚未补足的安全资金转入长期增长。",
      limits_growth: true,
      source_record_ids: ["asset-cash"],
    },
    {
      constraint_id: "behavior",
      constraint_type: "soft",
      name: "行为承受力修正",
      status: "pass",
      observed_value: "行为上限 medium",
      required_condition: "只能下调建议",
      effect: "不额外下调。",
      limits_growth: false,
      source_record_ids: ["behavior"],
    },
  ],
  accounts: [
    account(1, "daily_liquidity", "要花的钱", "50000.00", "133000.00", "133000.00", "83000.00"),
    account(2, "risk_protection", "保命的钱", "12000.00", "12000.00", "12000.00", "0.00"),
    account(3, "stable_goals", "保本的钱", "150000.00", "317468.61", "251000.00", "167468.61"),
    account(4, "long_term_growth", "生钱的钱", "120000.00", "0.00", "0.00", "0.00"),
  ],
  investment_learning: {
    applicable: true,
    eligible: false,
    cap_ratio: "0.100000",
    recommended_ratio: null,
    recommended_amount: "0.00",
    denominator_name: "完成前置安排与市场留存后的多余长期资金",
    denominator_value: "0.00",
    conditions: ["年度新增结余为正", "没有待处理的高息债务"],
    failed_conditions: ["完成前置安排后没有多余长期资金", "仍有待处理的高息债务"],
    explanation: "正式启动线尚未达到，当前也不满足小额学习仓条件。",
  },
  growth_70: {
    eligible: false,
    threshold: "0.700000",
    actual_ratio: "0.000000",
    denominator_name: "扣除优先债务后的可规划资源",
    denominator_id: "residual_long_term_plannable_capital",
    denominator_value: "396000.00",
    formal_growth_amount: "0.00",
    conditions: ["五项硬约束全部通过"],
    failed_conditions: ["流动性约束"],
    explanation: "当前不满足 70% 展示条件，不得套用于家庭总资产。",
  },
  growth_benchmark: {
    benchmark_rate: "0.050000",
    components: {
      consumer_price_observation: "0.020000",
      household_weighted_cost_growth: "0.050000",
      minimum_wage_auxiliary_signal: "0.030000",
    },
    formula: "max(消费价格观察, 家庭目标成本, 最低工资辅助信号)",
    explanation: "仅用于观察长期购买力，不是收益承诺。",
    minimum_wage_is_cpi: false,
    is_return_guarantee: false,
  },
  actions: [
    {
      priority: 1,
      action_code: "clear_high_interest_debt",
      title: "先清理高息债务",
      detail: "在新增长期投资前核对计息规则并完成清偿。",
      amount: "8000.00",
      due_date: "2026-09-03",
      account_bucket: null,
      source_record_ids: ["credit-card-unpaid"],
    },
  ],
  methodology: {
    framework_code: "chfh",
    framework_name: "中国家庭财富健康理论",
    optimization_objective: "提高家庭现金流连续性、风险保障、目标实现概率、财务韧性与长期实际购买力。",
    methodology_code: "chfh_grb_four_account_waterfall",
    methodology_version: "3.1.0",
    formula_version: "fortune-copilot-methodology-v3.1.0",
    constitution: [
      { code: "responsibility_first", title: "先责任，后投资", rule: "硬约束不可覆盖", hard: true },
    ],
    regional_threshold: {
      policy_version: "regional-growth-threshold-v1.0.0",
      region_code: "330100",
      region_name: "浙江省杭州市",
      city_tier: "tier_one_or_new_tier_one",
      policy_minimum: "300000.00",
      recommended_minimum: "560000.00",
      recommended_maximum: "710000.00",
      customer_selected_threshold: "500000.00",
      effective_threshold: "560000.00",
      explanation: "系统建议 56-71 万元；客户选择不能低于系统安全底线。",
      evidence: [
        { factor: "region", observed_value: "杭州", adjustment_amount: "0.00", explanation: "地区基准", source_record_ids: [] },
      ],
    },
    market_regime: {
      snapshot_version: "market-regime-demo-2026-08-04",
      regime: "neutral",
      label: "中性",
      valuation_date: "2026-08-04",
      effective_from: "2026-08-04",
      effective_to: "2026-12-31",
      source: "受控演示快照",
      methodology: "由投研治理发布",
      evidence: ["家庭责任优先"],
      rule_version: "market-policy-v1",
      approved_by: "demo_governance",
      is_demo: true,
      customer_editable: false,
      llm_generated: false,
    },
    minimum_wage_snapshot: {
      region_code: "330100",
      region_name: "浙江省杭州市",
      cagr: "0.030000",
      period_years: "4.000000",
      status: "available",
      source_reference: "受控演示时间序列",
      observed_at: "2026-01-01",
      version: "minimum-wage-demo-v1.0.0",
      is_live: false,
      is_demo: true,
      is_cpi: false,
    },
    purchasing_power_hurdle: {
      version: "pph@3.1.0",
      rate: "0.050000",
      formula: "max(CPI, family inflation, minimum wage CAGR)",
      components: [
        { code: "official_cpi_trend", label: "官方 CPI 趋势", rate: "0.020000", data_as_of: "2026-08-04", source: "demo", version: "v1", status: "available", is_cpi: true },
        { code: "family_weighted_expense_inflation", label: "家庭支出加权变化", rate: "0.050000", data_as_of: "2026-08-04", source: "confirmed goals", version: "v1", status: "available", is_cpi: false },
        { code: "regional_minimum_wage_cagr", label: "地区最低工资 CAGR", rate: "0.030000", data_as_of: "2026-01-01", source: "demo", version: "v1", status: "available", is_cpi: false },
      ],
      explanation: "PPH 是家庭层购买力目标，不是收益承诺。",
      minimum_wage_is_cpi: false,
      is_return_guarantee: false,
    },
    responsibility_ledger: {
      version: "responsibility-ledger-v1",
      entries: [],
      total_target_amount: "2986000.00",
      total_minimum_amount: "2200000.00",
      total_prepared_amount: "110000.00",
      total_institutional_coverage: "0.00",
      explanation: "将目标和债务统一为家庭责任。",
    },
    institutional_coverage: {
      version: "institutional-coverage-v1",
      social_security_balance: "50000.00",
      provident_fund_balance: "0.00",
      enterprise_annuity_balance: "0.00",
      occupational_annuity_balance: "0.00",
      personal_pension_balance: "30000.00",
      locked_balance: "30000.00",
      withdrawable_balance: "0.00",
      retirement_income_floor: { required_annual_floor: null, covered_annual_income: null, coverage_ratio: null, status: "needs_review", explanation: "缺少待遇预测" },
      explanation: "制度外壳与产品风险分开。",
    },
    personal_pension: {
      policy: { policy_version: "personal-pension-policy-v1.0.0", annual_contribution_limit: "12000.00", withdrawal_tax_rate: "0.030000", effective_from: "2026-01-01", effective_to: null, source_system: "controlled_demo_snapshot", source_reference: "版本化演示参数", observed_at: "2026-08-04", effective_at: "2026-01-01", ingested_at: "2026-08-04T00:00:00+08:00", version: "personal-pension-policy-v1.0.0", data_quality: "demo", is_live: false, is_demo: true, lineage: "controlled demo -> policy snapshot" },
      eligibility_status: "needs_review",
      annual_contribution_amount: "0.00",
      contribution_limit: "12000.00",
      contribution_progress_ratio: "0.000000",
      remaining_contribution_capacity: "12000.00",
      assumed_marginal_tax_rate: "0.100000",
      estimated_current_year_tax_benefit: "0.00",
      account_balance: "30000.00",
      product_risk_allocation: [],
      reminder_state: "review_eligibility",
      retirement_projection_status: "needs_more_data",
      explanation: "个人养老金是制度外壳，不自动等于低风险。",
    },
    property_policy: { policy_version: "property-policy-v1", status: "restricted_by_default", valuation_date: "2026-08-04", source: "demo", is_demo: true, rules: ["自住房不进入增长资本"] },
    financial_journey: { state: "financial_recovery", label: "财务修复", investment_mode: "no_investment_sales", explanation: "先修复安全底线。" },
    grb: {
      code: "grb",
      version: "grb-dynamic-account-v1.0.0",
      formula: "Allocation = π(Goal, Risk, Behavior, Household State)",
      goal_count: 3,
      rigid_goal_count: 2,
      nearest_goal_date: "2028-06-01",
      goal_status: "ready",
      goal_summary: "已识别 3 项有期限责任，其中 2 项为刚性责任。",
      risk_status: "ready",
      capacity_score: "0.580000",
      willingness_score: "0.632000",
      effective_risk_limit: "medium",
      risk_summary: "已读取客观风险承担能力、主观风险意愿和现行风险上限。",
      behavior_status: "ready",
      revealed_behavior_score: "0.503333",
      detected_biases: ["loss_aversion", "performance_chasing"],
      behavior_summary: "已完成问卷与下跌情景实验；行为结果只允许维持或下调风险预算。",
      behavior_can_only_downshift: true,
      formal_suitability_required: true,
    },
  },
  asset_liquidity: {
    daily_liquid_assets: "50000.00",
    liquid_stable_assets: "150000.00",
    withdrawable_institutional_assets: "0.00",
    locked_institutional_assets: "30000.00",
    growth_assets: "120000.00",
    locked_asset_ids: ["pension-asset"],
    withdrawable_asset_ids: [],
    explanation: "锁定养老金不能满足应急流动性。",
  },
  current_allocation_plan: {
    denominator_id: "investable_financial_assets",
    current_investable_balance: "320000.00",
    debt_settlement_from_current_balance: "8000.00",
    current_balance_available_after_debt: "312000.00",
    explanation: "今天的资产存量。",
  },
  contribution_plan: {
    denominator_id: "annual_new_surplus",
    annual_new_surplus: "72000.00",
    recorded_premium_reclassification: "12000.00",
    same_period_commitments: "0.00",
    future_contribution_available: "72000.00",
    explanation: "未来现金流不加入今天的可配置余额。",
  },
  protection_plan: {
    version: "protection-need-engine-v1",
    annual_premium_cost: "12000.00",
    premium_affordability_ratio: "0.020000",
    needs: [],
    savings_and_protection_split_required: false,
    explanation: "保额不进入可投资资产。",
  },
  decision_evidence: {
    evidence_version: "decision-evidence-package-v1.0.0",
    household_input_version: "fixture-planning-input",
    methodology_version: "3.1.0",
    financial_rule_version: "1.0.0",
    planning_rule_version: "2.2.0",
    regional_parameter_version: "regional-growth-threshold-v1.0.0",
    market_regime_version: "market-regime-demo-2026-08-04",
    minimum_wage_snapshot_version: "minimum-wage-demo-v1.0.0",
    pension_policy_version: "personal-pension-policy-v1.0.0",
    portfolio_version: "not_applicable_planning_stage",
    product_snapshot_version: "not_applicable_planning_stage",
    risk_assessment_version: "risk-v1",
    behavior_assessment_version: "behavior-v1",
    llm_model_version: null,
    llm_prompt_version: null,
    hard_gate_results: { liquidity: "block" },
    generated_at: "2026-08-04T00:00:00Z",
    decision_hash: "fixture-decision-hash",
    calculation_source: "deterministic_tools",
  },
  applied_counterfactual: {
    emergency_fund_addition: "0.00",
    high_interest_debt_reduction: "0.00",
    protection_gap_reduction: "0.00",
    monthly_savings_increase: "0.00",
    goal_prepared_additions: {},
    defer_goal_ids: [],
    defer_months: 0,
    lifecycle_override: null,
  },
  counting_note: "四账户采用顺序式资金瀑布；保额、信用卡额度与住房不重复计入。",
};
