import type {
  AccountAllocation,
  PlanningResponse,
  RatioMeasure,
  WaterfallStep,
} from "../api/planning";

function measures(amount: string): RatioMeasure[] {
  return [
    {
      denominator_id: "total_assets",
      denominator_name: "家庭总资产",
      denominator_value: "2850000.00",
      ratio: (Number(amount) / 2_850_000).toFixed(6),
      applicable: true,
      reason: `${amount} ÷ 2850000.00`,
    },
    {
      denominator_id: "investable_financial_assets",
      denominator_name: "可投资金融资产",
      denominator_value: "320000.00",
      ratio: (Number(amount) / 320_000).toFixed(6),
      applicable: true,
      reason: `${amount} ÷ 320000.00`,
    },
    {
      denominator_id: "annual_new_surplus",
      denominator_name: "年度新增结余",
      denominator_value: "72000.00",
      ratio: (Number(amount) / 72_000).toFixed(6),
      applicable: true,
      reason: `${amount} ÷ 72000.00`,
    },
  ];
}

function account(
  sequence: number,
  bucket: AccountAllocation["bucket"],
  name: string,
  current: string,
  target: string,
  recommended: string,
  gap: string,
): AccountAllocation {
  return {
    bucket,
    name,
    sequence,
    current_amount: current,
    target_amount: target,
    recommended_amount: recommended,
    recommended_range_min: recommended,
    recommended_range_max: target,
    gap_amount: gap,
    annual_cost_amount: bucket === "risk_protection" ? "12000.00" : "0.00",
    coverage_gap_amount: bucket === "risk_protection" ? "1452000.00" : "0.00",
    primary_denominator_name: "可投资金融资产",
    reference_band:
      bucket === "stable_goals"
        ? {
            denominator_id: "investable_financial_assets",
            denominator_name: "可投资金融资产",
            minimum_ratio: "0.100000",
            maximum_ratio: "0.200000",
            target_ratio: "0.150000",
            overall_minimum_ratio: "0.050000",
            overall_maximum_ratio: "0.300000",
            market_regime: "neutral",
            market_regime_label: "中性",
            binding: false,
            conditions: ["无明确近期目标缺口时参考"],
            explanation: "中性口径为 10%—20%，全周期 5%—30% 不是固定比例。",
          }
        : null,
    current_measures: measures(current),
    target_measures: measures(target),
    measures: measures(recommended),
    formula: "按七步顺序计算，再应用五硬一软约束",
    substitution: `${current} → ${recommended}`,
    rationale: "根据家庭目标、期限和安全闸门动态生成。",
    constraint_ids: ["liquidity"],
    source_record_ids: ["fixture-record"],
    product_education: [
      bucket === "daily_liquidity"
        ? "信用卡额度不是资产，不计入日用资金。"
        : "产品风险、期限和流动性需逐项评估。",
    ],
  };
}

const stepNames = [
  "高息债务处理",
  "日常资金",
  "应急储备",
  "必要保障成本",
  "一年内确定支出",
  "一至五年刚性目标",
  "剩余长期资金",
];

const waterfallSteps: WaterfallStep[] = stepNames.map((name, index) => ({
  sequence: index + 1,
  step_code: `step-${index + 1}`,
  name,
  required_amount: index === 0 ? "8000.00" : "12000.00",
  allocated_amount: index === 6 ? "0.00" : "12000.00",
  remaining_resources: "0.00",
  status: index === 5 ? "partial" : "covered",
  formula: "顺序分配",
  explanation: "前一层完成后才进入下一层。",
  source_record_ids: ["fixture-record"],
}));

export const planningFixture: PlanningResponse = {
  meta: {
    household_id: "household-b",
    household_code: "DEMO_B",
    analysis_date: "2026-08-04",
    data_as_of: "2025-12-31",
    input_version: "fixture-planning-input",
    formula_version: "fortune-copilot-four-account-v2.2.0",
    rule_code: "dynamic_account_waterfall",
    rule_version: "2.2.0",
    rule_source_type: "internal_demo",
    calculation_source: "deterministic_tools",
    currency: "CNY",
    synthetic_data: true,
    scenario_type: "base",
  },
  lifecycle: {
    detected_stage: "parenting",
    recorded_stage: "parenting",
    effective_stage: "parenting",
    override_applied: false,
    dynamic_safety_months: "7.00",
    base_safety_months: "5.00",
    formula: "基础月数 + 家庭责任修正",
    substitution: "5 - 0.5 - 0.5 + 1 + 1 + 1 = 7",
    explanation: "家庭存在未成年子女。",
    evidence: [],
  },
  goals: [
    {
      goal_id: "goal-education",
      name: "子女教育",
      goal_type: "education",
      target_date: "2036-08-04",
      adjusted_target_date: "2036-08-04",
      months_remaining: 120,
      current_cost: "600000.00",
      future_amount: "988205.70",
      present_value: "809209.10",
      minimum_present_value: "606906.82",
      prepared_amount: "80000.00",
      funding_gap: "729209.10",
      minimum_funding_gap: "526906.82",
      monthly_required: "6076.74",
      annual_required: "72920.88",
      priority: 1,
      rigidity: "rigid",
      can_defer: false,
      annual_cost_growth_rate: "0.050000",
      status: "conflict",
      formula: "未来金额和现值分别复利计算",
      substitution: "未来 988,205.70；现值 809,209.10；(809,209.10 − 80,000.00) ÷ 120 = 6,076.74/月",
      source_record_ids: ["goal-education"],
    },
    {
      goal_id: "goal-retirement",
      name: "夫妻退休养老",
      goal_type: "retirement",
      target_date: "2051-05-20",
      adjusted_target_date: "2051-05-20",
      months_remaining: 298,
      current_cost: "2000000.00",
      future_amount: "4208967.97",
      present_value: "2562451.05",
      minimum_present_value: "1921838.29",
      prepared_amount: "30000.00",
      funding_gap: "2532451.05",
      minimum_funding_gap: "1891838.29",
      monthly_required: "8498.16",
      annual_required: "101977.92",
      priority: 2,
      rigidity: "important",
      can_defer: true,
      annual_cost_growth_rate: "0.030000",
      status: "conflict",
      formula: "未来金额和现值分别复利计算",
      substitution: "2562451.05 - 30000.00 = 2532451.05",
      source_record_ids: ["goal-retirement"],
    },
  ],
  conflicts: [
    {
      conflict_id: "monthly_goal_capacity",
      severity: "warning",
      title: "目标月投入超过当前新增结余",
      detail: "全部目标需求超过每月可持续结余。",
      affected_goal_ids: ["goal-education", "goal-retirement"],
      available_monthly_surplus: "6000.00",
      required_monthly_contribution: "13640.79",
      monthly_shortfall: "7640.79",
      adjustments: [
        {
          action_code: "defer_goal",
          title: "评估退休目标延期 12 个月",
          detail: "延期后月投入下降，但不隐藏目标缺口。",
          affected_goal_ids: ["goal-retirement"],
          monthly_effect: "330.00",
          preserves_minimum: true,
        },
      ],
    },
  ],
  denominators: {
    total_assets: "2850000.00",
    investable_financial_assets: "320000.00",
    net_financial_assets_after_debt: "-858600.00",
    growth_entry_threshold: "500000.00",
    annual_new_surplus: "72000.00",
    available_planning_resources: "404000.00",
    high_interest_debt_before_plan: "8000.00",
    high_interest_debt_after_counterfactual: "8000.00",
    same_period_cashflow_committed: "0.00",
  },
  waterfall_steps: waterfallSteps,
  constraints: [
    {
      constraint_id: "liquidity",
      constraint_type: "hard",
      name: "流动性约束",
      status: "block",
      observed_value: "当前日用与即时资产 50,000.00",
      required_condition: "达到动态日用目标 133,000.00",
      effect: "阻止把尚未补足的安全资金转入长期增长。",
      limits_growth: true,
      source_record_ids: ["asset-cash"],
    },
    {
      constraint_id: "behavior",
      constraint_type: "soft",
      name: "行为承受力修正",
      status: "pass",
      observed_value: "行为上限 medium",
      required_condition: "只能下调建议",
      effect: "不额外下调。",
      limits_growth: false,
      source_record_ids: ["behavior"],
    },
  ],
  accounts: [
    account(1, "daily_liquidity", "要花的钱", "50000.00", "133000.00", "133000.00", "83000.00"),
    account(2, "risk_protection", "保命的钱", "12000.00", "12000.00", "12000.00", "0.00"),
    account(3, "stable_goals", "保本的钱", "150000.00", "317468.61", "251000.00", "167468.61"),
    account(4, "long_term_growth", "生钱的钱", "120000.00", "0.00", "0.00", "0.00"),
  ],
  investment_learning: {
    applicable: true,
    eligible: false,
    cap_ratio: "0.100000",
    recommended_ratio: null,
    recommended_amount: "0.00",
    denominator_name: "完成前置安排与市场留存后的多余长期资金",
    denominator_value: "0.00",
    conditions: ["年度新增结余为正", "没有待处理的高息债务"],
    failed_conditions: ["完成前置安排后没有多余长期资金", "仍有待处理的高息债务"],
    explanation: "正式启动线尚未达到，当前也不满足小额学习仓条件。",
  },
  growth_70: {
    eligible: false,
    threshold: "0.700000",
    actual_ratio: "0.000000",
    denominator_name: "扣除优先债务后的可规划资源",
    denominator_value: "396000.00",
    conditions: ["五项硬约束全部通过"],
    failed_conditions: ["流动性约束"],
    explanation: "当前不满足 70% 展示条件，不得套用于家庭总资产。",
  },
  growth_benchmark: {
    benchmark_rate: "0.050000",
    components: {
      consumer_price_observation: "0.020000",
      household_weighted_cost_growth: "0.050000",
      minimum_wage_auxiliary_signal: "0.030000",
    },
    formula: "max(消费价格观察, 家庭目标成本, 最低工资辅助信号)",
    explanation: "仅用于观察长期购买力，不是收益承诺。",
    minimum_wage_is_cpi: false,
    is_return_guarantee: false,
  },
  actions: [
    {
      priority: 1,
      action_code: "clear_high_interest_debt",
      title: "先清理高息债务",
      detail: "在新增长期投资前核对计息规则并完成清偿。",
      amount: "8000.00",
      due_date: "2026-09-03",
      account_bucket: null,
      source_record_ids: ["credit-card-unpaid"],
    },
  ],
  applied_counterfactual: {
    emergency_fund_addition: "0.00",
    high_interest_debt_reduction: "0.00",
    protection_gap_reduction: "0.00",
    monthly_savings_increase: "0.00",
    goal_prepared_additions: {},
    defer_goal_ids: [],
    defer_months: 0,
    lifecycle_override: null,
  },
  counting_note: "四账户采用顺序式资金瀑布；保额、信用卡额度与住房不重复计入。",
};
