import type { CFSProductCompositionResponse } from "../api/productOntology";

export const productOntologyFixture = {
  household_id: "household-c",
  solution_id: "solution-c",
  analysis_date: "2026-08-10",
  catalog_as_of: "2026-08-07",
  catalog_stale: false,
  executable_recommendation_allowed: false,
  groups: [
    {
      component_id: "component-protection",
      component_type: "protection",
      purpose: "先核对保障缺口与可持续保费。",
      result: "no_product",
      candidates: [],
      excluded: [],
      funnel: null,
      no_product_reason: "该行动不需要产品映射；专业服务本身就是正确承接方式。",
    },
    {
      component_id: "component-investment",
      component_type: "investment",
      purpose: "仅使用通过前置责任扣减和适当性门的 ELTC 进入长期配置。",
      result: "ranked",
      no_product_reason: null,
      funnel: {
        stages: [
          { code: "sample_pool", label: "产品样本池", count: 8 },
          { code: "need_fit", label: "用途匹配", count: 5 },
          { code: "horizon_fit", label: "期限匹配", count: 5 },
          { code: "risk_suitability", label: "风险适当性", count: 3 },
          { code: "liquidity_fit", label: "流动性要求", count: 3 },
          { code: "quality_filters", label: "费用 / 资格 / 冲突过滤", count: 2 },
          { code: "final_candidates", label: "最终候选", count: 1 },
        ],
        calculation_source: "deterministic_product_engine",
        explanation: "各阶段数量由同一产品资格与排序上下文逐层计算。",
      },
      excluded: [
        {
          product_id: "product-excluded",
          product_code: "EXCLUDED-001",
          product_name: "期限不匹配示例产品",
          decision: "blocked",
          reasons: ["最短持有期长于目标期限。"],
        },
      ],
      candidates: [
        {
          rank: 1,
          product: {
            id: "product-005102",
            code: "005102",
            name: "工银瑞信沪深300交易型开放式指数证券投资基金联接基金A类基金份额",
            issuer: "工银瑞信基金管理有限公司",
            jurisdiction: "CN",
            currency: "CNY",
            product_family: "equity_index_fund",
            product_subtype: "domestic_broad_index",
            asset_class: "equity",
            risk_level: "r3",
            liquidity_level: "within_7_days",
            minimum_investment: "0.00",
            minimum_holding_months: 0,
            redemption_rules: "到账规则以销售文件及工行当日页面为准。",
            all_in_cost: null,
            distribution_incentive_disclosure: "公开目录未提供客户全口径费用和渠道激励；执行前必须补充核验。",
            conflict_of_interest_flag: false,
            professional_review_required: false,
            client_role_in_cfs: ["long_term_growth"],
            account_wrappers: ["ordinary"],
            complexity_level: "standard",
            principal_loss_possible: true,
            legally_principal_guaranteed: false,
            enabled: true,
            classification_version: "product-ontology-v1",
            evidence_json: { source_type: "verified_real_public_funds" },
          },
          snapshot: {
            id: "snapshot-005102",
            product_id: "product-005102",
            as_of_date: "2026-08-07",
            sale_status: "channel_verification_required",
            risk_level: "r3",
            fee_snapshot: { all_in_cost: null },
            liquidity_snapshot: { minimum_holding_days: 0, lock_up: false },
            terms_snapshot: { broad_index: true },
            channel: "icbc_public_listing",
            source_reference: "https://www.icbc.com.cn/example",
            evidence: [],
            snapshot_hash: "snapshot-hash",
            snapshot_version: "catalog@1.0.0:005102",
          },
          eligibility: {
            decision: "restricted",
            eligible: false,
            executable: false,
            reasons: ["产品可进入候选比较，但限制项补齐前不能执行。"],
            restrictions: ["公开列示不等于当日可售，需在交易渠道再次核验。", "客户全口径费用尚未补齐。"],
            freshness: {
              as_of_date: "2026-08-07",
              age_days: 3,
              maximum_age_days: 45,
              stale: false,
              sale_status: "channel_verification_required",
              executable: false,
            },
          },
          score: "88",
          why_selected: ["产品用途覆盖当前 CFS 需要。", "风险等级未超过家庭风险预算。"],
          why_not_other_candidates: ["其他候选的成本或分散度得分更低。"],
        },
      ],
    },
  ],
  execution_boundary: "候选来自经核验的公开基金资料，不代表当前账户可售、适当性通过或已经获得交易授权。",
} satisfies CFSProductCompositionResponse;
